/*
 * Crows (MCDM) Playtest 2 — game data used by the character generator.
 * Source: "02 Crows Characters Book for Playtest 2", "01 Crows The Rules Book for Playtest 2",
 * the Playtest 2 inventory cards, and the Ref Book bestiary (pets).
 */

var CROWS = {};

CROWS.CHARS = ['Agility', 'Mind', 'Strength'];
CROWS.CHAR_ABBR = { Agility: 'A', Mind: 'M', Strength: 'S' };
CROWS.BASE_SPEED = 5;

CROWS.EXPERTISES = {
  General: [
    ['Alchemy', 'Make and know about potions, poisons, and bombs'],
    ['Athletics', 'Climb, jump, and swim'],
    ['Blacksmithing', 'Make and know about metal tools, armor, and weapons'],
    ['Enchanting', 'Make and know about magic items'],
    ['Endurance', 'Remain engaged in strenuous physical or mental activity for a long time'],
    ['Gymnastics', 'Move across unsteady or narrow surfaces; tumble'],
    ['Handle Pet', 'Interact with pets'],
    ['Historical Lore', 'Know about significant past events'],
    ['Lift', 'Pick up, carry, and throw heavy objects'],
    ['Magic Lore', 'Know about magical places, spells, items, and phenomena'],
    ['Monster Lore', 'Know monster ecology, strengths, and weaknesses'],
    ['Nature Lore', 'Know about natural flora, fauna, and weather'],
    ['Navigate', 'Travel without getting lost'],
    ['Pick Lock', 'Open a lock without the key'],
    ['Religious Lore', 'Know about religious mythology and practices'],
    ['Search', 'Search an environment for important details and items'],
    ['Stealth', 'Hide and sneak'],
    ['Thievery', 'Disable mechanical devices, open locks, pick pockets, and general sleight of hand']
  ],
  Spellcasting: [
    ['Alteration', 'Cast alteration spells'],
    ['Benefaction', 'Cast benefaction spells'],
    ['Conjuration', 'Cast conjuration spells'],
    ['Elemental', 'Cast elemental spells'],
    ['Illusion', 'Cast illusion spells'],
    ['Necromancy', 'Cast necromancy spells']
  ],
  Weapon: [
    ['Bashing', 'Attack with bashing weapons'],
    ['Bow', 'Attack with bow weapons'],
    ['Chopping', 'Attack with chopping weapons'],
    ['Slashing', 'Attack with slashing weapons'],
    ['Stabbing', 'Attack with stabbing weapons'],
    ['Unarmed', 'Attack with natural weapons']
  ]
};

/* Starting kit every PC gets (Characters Book, step 3). */
CROWS.STANDARD_KIT = [['Coin Purse', 1], ['Knife', 1], ['Rope', 1], ['Ration', 6]];

/*
 * Backgrounds. d = [left d6, right d6]; two = characteristic(s) the background can set to 2
 * (array of choices); exp = expertise uses; gear = [item, qty]; pets = pet names; gc = extra gold.
 */
CROWS.BACKGROUNDS = [
  { name: 'Acolyte of the Gardner', d: [1, 1], blurb: 'You served the god of nature.', two: ['Mind'], stamina: 5,
    trait: ['Enchantment', 'Material Transfer'],
    exp: { 'Athletics': 1, 'Handle Pet': 1, 'Nature Lore': 1, 'Navigate': 1, 'Religious Lore': 1, 'Benefaction': 2, 'Elemental': 2 },
    gear: [['Holy Symbol', 1], ['Torch', 1], ['Fire Hands Book', 1], ['Minor Healing Book', 1], ['Spark Book', 1]] },
  { name: 'Acolyte of the Healer', d: [1, 2], blurb: 'You served the god of healing.', two: ['Mind'], stamina: 7,
    trait: ['Benefaction', 'Enhanced Healing'],
    exp: { 'Alchemy': 1, 'Lift': 1, 'Religious Lore': 2, 'Benefaction': 2 },
    gear: [['Holy Symbol', 1], ['Surgical Kit', 1], ['Torch', 1], ['Minor Blessing Book', 1], ['Minor Healing Book', 1]] },
  { name: 'Acolyte of the Smith', d: [1, 3], blurb: 'You served the god of creativity.', two: ['Mind'], stamina: 7,
    trait: ['Enchantment', 'Hands for Tools'],
    exp: { 'Alchemy': 1, 'Blacksmithing': 2, 'Enchanting': 1, 'Religious Lore': 1, 'Benefaction': 1 },
    gear: [["Blacksmith's Tools", 1], ['Holy Symbol', 1], ['Torch', 1], ['Minor Healing Book', 1], ['Summon Object Book', 1]] },
  { name: 'Acolyte of the Three', d: [1, 4], blurb: 'You served the god of death, greed, and knowledge.', two: ['Mind', 'Strength'], stamina: 7,
    trait: ['Necromancy', 'Soul Absorption'],
    exp: { 'Magic Lore': 1, 'Monster Lore': 1, 'Religious Lore': 1, 'Necromancy': 2, 'Chopping': 1 },
    gear: [['Axe', 1], ['Torch', 1], ['Bone Capture Book', 1], ['Minor Curse Book', 1], ['Monster Sense Book', 1]] },
  { name: 'Acolyte of the Warrior', d: [1, 5], blurb: 'You served the god of war.', two: ['Mind', 'Strength'], stamina: 9,
    trait: ['Benefaction', 'First Responder'],
    exp: { 'Religious Lore': 1, 'Benefaction': 1, 'Chopping': 1 },
    gear: [['Axe', 1], ['Holy Symbol', 1], ['Torch', 1], ['Minor Healing Book', 1], ['Minor Ward Book', 1]] },
  { name: 'Alchemist', d: [1, 6], blurb: 'You crafted and sold acids, potions, and bombs.', two: ['Mind'], stamina: 5,
    trait: ['Alchemy', 'Midnight Oil'],
    exp: { 'Alchemy': 2, 'Enchanting': 1, 'Magic Lore': 1, 'Monster Lore': 1, 'Nature Lore': 1, 'Search': 1, 'Thievery': 2 },
    gear: [['Acid Vial', 1], ["Alchemist's Tools", 1], ['Bucket', 1], ['Healing Potion', 1], ['Lantern', 1], ['Oil Flask', 1], ['Smoke Bomb', 1]] },
  { name: 'Apprentice Mage', d: [2, 1], blurb: 'You studied several magic disciplines under a more experienced tutor.', two: ['Mind'], stamina: 5,
    trait: ['Alteration', 'Alteration Stone'],
    exp: { 'Enchanting': 1, 'Magic Lore': 1, 'Monster Lore': 1, 'Alteration': 2, 'Conjuration': 1, 'Elemental': 2, 'Illusion': 1 },
    gear: [['Alteration Stone', 1], ['Jaunt Book', 1], ['Light Book', 1], ['Spark Book', 1], ['Take Shape Book', 1], ['Thunder Book', 1]] },
  { name: 'Archer', d: [2, 2], blurb: 'You served as a soldier or member of the watch who was specially trained with a bow.', two: ['Agility'], stamina: 7,
    trait: ['Archery', 'Point Blank'],
    exp: { 'Athletics': 1, 'Stealth': 2, 'Bow': 2, 'Unarmed': 1 },
    gear: [['Bear Trap', 1], ['Quiver of 20 Arrows', 1], ['Shortbow', 1], ['Spyglass', 1], ['Torch', 1]] },
  { name: 'Assassin', d: [2, 3], blurb: 'You were a killer who either worked paid contracts or served a higher purpose in a shady organization.', two: ['Agility'], stamina: 5,
    trait: ['Thievery', 'Sieze the Advantage'],
    exp: { 'Athletics': 1, 'Gymnastics': 1, 'Stealth': 2, 'Thievery': 1, 'Bow': 2, 'Slashing': 2 },
    gear: [['Knife', 1], ['Poison Vial', 1], ['Quiver of 20 Arrows', 1], ['Shortbow', 1], ['Torch', 1]] },
  { name: 'Beggar', d: [2, 4], blurb: 'You relied on the kindness of strangers to scrape together enough coins to live.', two: ['Agility', 'Mind', 'Strength'], stamina: 7,
    trait: ['Leverage', 'More for Less'],
    exp: { 'Endurance': 1, 'Lift': 1, 'Search': 2, 'Stealth': 2 },
    gear: [['Glue Pot', 1], ['Padlock', 1], ['Pot', 1], ['String', 1], ['Tent', 1], ['Torch', 1]] },
  { name: 'Blacksmith', d: [2, 5], blurb: 'You forged and sold items made from metal.', two: ['Strength'], stamina: 7,
    trait: ['Blacksmithing', 'Double Duty'],
    exp: { 'Blacksmithing': 2, 'Endurance': 1, 'Lift': 1, 'Thievery': 1, 'Bashing': 1 },
    gear: [['Bear Trap', 1], ["Blacksmith's Tools", 1], ['Chain', 1], ['Maul', 1], ['Torch', 1]] },
  { name: 'Bodyguard', d: [2, 6], blurb: 'You protected a person of importance.', two: ['Strength'], stamina: 9,
    trait: ['Armor', 'Interposing Arm'],
    exp: { 'Endurance': 1, 'Search': 1, 'Slashing': 1 },
    gear: [['Ball Bearings', 1], ['Light Armor', 1], ['Shield', 1], ['Sword', 1], ['Torch', 1]] },
  { name: 'Cartographer', d: [3, 1], blurb: 'You drew maps of villages, ruins, or wilderness areas so others could find their way.', two: ['Mind'], stamina: 7,
    trait: ['Travel', 'Orienteering'],
    exp: { 'Historical Lore': 1, 'Monster Lore': 1, 'Nature Lore': 1, 'Navigate': 2, 'Search': 1 },
    gear: [['Compass', 1], ['Journal', 1], ['Lantern', 1], ['Lore Book (Historical Lore)', 1], ['Oil Flask', 1], ['Quill & Inkpot', 1]] },
  { name: 'Conjurer', d: [3, 2], blurb: 'You studied conjuration magic.', two: ['Mind'], stamina: 7,
    trait: ['Conjuration', 'Jumper'],
    exp: { 'Handle Pet': 1, 'Magic Lore': 1, 'Monster Lore': 1, 'Navigate': 1, 'Conjuration': 2 },
    gear: [['Chain', 1], ['Torch', 1], ['Jaunt Book', 1], ['Summon Object Book', 1], ['Teleport Object Book', 1]] },
  { name: 'Cook', d: [3, 3], blurb: 'You worked as a cook at a tavern or organization.', two: ['Agility', 'Mind', 'Strength'], stamina: 7,
    trait: ['Camping', 'Hearty Meals'],
    exp: { 'Alchemy': 1, 'Endurance': 1, 'Lift': 1, 'Nature Lore': 2, 'Slashing': 1 },
    gear: [["Cook's Utensils", 1], ['Hearty Ration', 2], ['Pot', 1], ['Torch', 1]] },
  { name: 'Duelist', d: [3, 4], blurb: 'You dedicated your youth to fencing in noble courts.', two: ['Agility'], stamina: 9,
    trait: ['Slashing', 'Finesse the Blade'],
    exp: { 'Gymnastics': 1, 'Historical Lore': 1, 'Slashing': 1 },
    gear: [['Light Armor', 1], ['Lore Book (Historical Lore)', 1], ['Mirror', 1], ['Sword', 1], ['Torch', 1]] },
  { name: 'Entertainer', d: [3, 5], blurb: 'You were an acrobat, dancer, and/or musician.', two: ['Agility'], stamina: 5,
    trait: ['Camping', 'Song of Rest'],
    exp: { 'Athletics': 2, 'Endurance': 1, 'Gymnastics': 2, 'Handle Pet': 1, 'Historical Lore': 1, 'Thievery': 2 },
    gear: [['11-Foot Pole', 1], ['Mirror', 1], ['Musical Instrument (Lute)', 1], ['Smoke Bomb', 1], ['Torch', 1]] },
  { name: 'Executioner', d: [3, 6], blurb: 'You carried out capital punishment.', two: ['Strength'], stamina: 9,
    trait: ['Chopping', "Chop 'Em Down"],
    exp: { 'Lift': 1, 'Chopping': 1, 'Unarmed': 1 },
    gear: [['Chain', 1], ['Greataxe', 1], ['Ladder', 1], ['Padlock', 1], ['Torch', 1]] },
  { name: 'Farmer', d: [4, 1], blurb: 'You plowed the fields and raised animals.', two: ['Strength'], stamina: 7,
    trait: ['Pets', 'Buddy'],
    exp: { 'Blacksmithing': 1, 'Endurance': 1, 'Handle Pet': 2, 'Lift': 1, 'Nature Lore': 1 },
    gear: [['11-Foot Pole', 1], ['Animal Feed', 6], ['Pot', 1], ['Torch', 1]], pets: ['Goat'] },
  { name: 'Gladiator', d: [4, 2], blurb: 'You fought deadly battles for the entertainment of others.', two: ['Strength'], stamina: 9,
    trait: ['Stabbing', 'Bury the Point'],
    exp: { 'Athletics': 1, 'Lift': 1, 'Stabbing': 1 },
    gear: [['Light Armor', 1], ['Mirror', 1], ['Pike', 1], ['Rage Potion', 1], ['Torch', 1]] },
  { name: 'Hunter', d: [4, 3], blurb: 'You tracked animals in the wild and foraged for food.', two: ['Agility'], stamina: 5,
    trait: ['Travel', 'Foraging Expert'],
    exp: { 'Athletics': 1, 'Handle Pet': 2, 'Nature Lore': 2, 'Navigate': 1, 'Stealth': 1, 'Bow': 2 },
    gear: [['Animal Feed', 6], ['Bear Trap', 1], ['Quiver of 20 Arrows', 1], ['Shortbow', 1], ['Torch', 1]], pets: ['Dog'] },
  { name: 'Hydromancer', d: [4, 4], blurb: 'You learned how to cast elemental spells that create and harness water.', two: ['Mind'], stamina: 7,
    trait: ['Elemental', 'Water Shield'],
    exp: { 'Alchemy': 1, 'Athletics': 1, 'Enchanting': 1, 'Magic Lore': 1, 'Elemental': 2 },
    gear: [['Glue Pot', 1], ['Journal', 1], ['Quill & Inkpot', 1], ['Torch', 1], ['Create Water Book', 1], ['Stream Book', 1]] },
  { name: 'Illusionist', d: [4, 5], blurb: 'You studied illusion magic.', two: ['Mind'], stamina: 5,
    trait: ['Illusion', 'Lasting Illusion'],
    exp: { 'Magic Lore': 2, 'Monster Lore': 1, 'Search': 1, 'Stealth': 2, 'Thievery': 1, 'Illusion': 2 },
    gear: [['Card Deck', 1], ['Smoke Bomb', 1], ['Whistle', 1], ['Cacophony Book', 1], ['Light Book', 1], ['Minor Phantasm Book', 1]] },
  { name: 'Keraunomancer', d: [4, 6], blurb: 'You learned how to cast elemental spells that create and harness lightning and thunder.', two: ['Mind'], stamina: 7,
    trait: ['Elemental', 'Hurl the Storm'],
    exp: { 'Blacksmithing': 1, 'Enchanting': 1, 'Magic Lore': 2, 'Elemental': 2, 'Bashing': 1 },
    gear: [['Mace', 1], ['Net', 1], ['Torch', 1], ['Spark Book', 1], ['Thunder Book', 1]] },
  { name: 'Knight', d: [5, 1], blurb: 'You were a knight in the service of a noble or a hedge knight in service to no one other than yourself.', two: ['Strength'], stamina: 9,
    trait: ['Slashing', 'Swordplay'],
    exp: { 'Handle Pet': 1, 'Historical Lore': 1, 'Slashing': 1 },
    gear: [['Animal Feed', 6], ['Greatsword', 1], ['Lantern', 1], ['Light Armor', 1], ['Oil Flask', 1]], pets: ['Riding Horse'] },
  { name: 'Merchant', d: [5, 2], blurb: 'You were a merchant who traveled from village to village, trading your wares.', two: ['Mind'], stamina: 7,
    trait: ['Camping', 'Plotting'],
    exp: { 'Historical Lore': 2, 'Lift': 1, 'Navigate': 1, 'Search': 1, 'Thievery': 1 },
    gear: [['Journal', 1], ['Lantern', 1], ["Merchant's Scales", 1], ['Oil Flask', 1], ['Quill & Inkpot', 1]], gc: 50 },
  { name: 'Miner', d: [5, 3], blurb: 'You worked in mines, digging and hauling ore.', two: ['Strength'], stamina: 7,
    trait: ['Leverage', 'Lasting Light'],
    exp: { 'Athletics': 1, 'Endurance': 2, 'Lift': 1, 'Navigate': 1, 'Stabbing': 1 },
    gear: [['Chalk', 1], ['Grappling Hook', 1], ['Lantern', 1], ['Oil Flask', 1], ['Shovel', 1], ['Warpick', 1]] },
  { name: 'Noble', d: [5, 4], blurb: 'You grew up in a family that had wealth and power.', two: ['Agility', 'Mind'], stamina: 7,
    trait: ['Reputation', 'Call Daddy'],
    exp: { 'Handle Pet': 1, 'Historical Lore': 2, 'Religious Lore': 1, 'Stealth': 1, 'Bow': 1 },
    gear: [['Animal Feed', 6], ['Lantern', 1], ['Lore Book (Historical Lore)', 1], ['Oil Flask', 1]], pets: ['Riding Horse'], gc: 50 },
  { name: 'Pugilist', d: [5, 5], blurb: 'You made a living battling it out with bare knuckles.', two: ['Agility', 'Strength'], stamina: 9,
    trait: ['Unarmed', 'Pack a Punch'],
    exp: { 'Athletics': 1, 'Unarmed': 2 },
    gear: [['Chalk', 1], ['Light Armor', 1], ['Lore Book (Monster Lore)', 1], ['Net', 1], ['Rage Potion', 1], ['Torch', 1]] },
  { name: 'Pyromancer', d: [5, 6], blurb: 'You learned how to cast elemental spells that create and harness fire.', two: ['Mind'], stamina: 5,
    trait: ['Elemental', 'Burn Baby'],
    exp: { 'Alchemy': 1, 'Enchanting': 1, 'Historical Lore': 1, 'Magic Lore': 2, 'Elemental': 2 },
    gear: [['Magnifying Glass', 1], ['Smoke Bomb', 1], ['String', 1], ['Torch', 1], ['Fire Hands Book', 1], ['Fire Lance Book', 1]] },
  { name: 'Sage', d: [6, 1], blurb: 'You studied all subjects with a tutor or by burying your nose in many books (likely both).', two: ['Mind'], stamina: 5,
    trait: ['Knowledge', 'Cram'],
    exp: { 'Historical Lore': 2, 'Magic Lore': 1, 'Monster Lore': 2, 'Nature Lore': 1, 'Navigate': 1, 'Religious Lore': 1, 'Thievery': 1 },
    gear: [['Ball Bearings', 1], ['Journal', 1], ['Lore Book (Monster Lore)', 1], ['Lore Book (Nature Lore)', 1], ['Quill & Inkpot', 1], ['Torch', 1]] },
  { name: 'Soldier', d: [6, 2], blurb: 'You served as a soldier in an army dedicated to protecting others from the threats of the wilderness.', two: ['Strength'], stamina: 9,
    trait: ['Armor', 'Stalwart'],
    exp: { 'Endurance': 1, 'Bow': 1, 'Stabbing': 1 },
    gear: [['Light Armor', 1], ['Quiver of 20 Arrows', 1], ['Shortbow', 1], ['Spear', 1], ['Torch', 1]] },
  { name: 'Thief', d: [6, 3], blurb: 'You burgled places for money, either on your own or as part of a guild.', two: ['Agility'], stamina: 5,
    trait: ['Thievery', 'Stealthy'],
    exp: { 'Athletics': 1, 'Gymnastics': 2, 'Search': 2, 'Stealth': 2, 'Thievery': 2 },
    gear: [['Crowbar', 1], ['Knife', 1], ['Grappling Hook', 1], ['Lockpick Set', 1], ['Smoke Bomb', 1], ['Torch', 1]] },
  { name: 'Tinkerer', d: [6, 4], blurb: 'You created magic and mechanical inventions.', two: ['Mind'], stamina: 5,
    trait: ['Knowledge', 'Improvised Equipment'],
    exp: { 'Alchemy': 2, 'Blacksmithing': 2, 'Enchanting': 1, 'Search': 1, 'Thievery': 2, 'Chopping': 1 },
    gear: [["Alchemist's Tools", 1], ["Blacksmith's Tools", 1], ['Handaxe', 1], ['Lockpick Set', 1], ['Soap', 1], ['Torch', 1]] },
  { name: 'Transmuter', d: [6, 5], blurb: 'You studied alteration magic.', two: ['Mind'], stamina: 5,
    trait: ['Alteration', 'Lasting Alteration'],
    exp: { 'Alchemy': 1, 'Blacksmithing': 1, 'Enchanting': 2, 'Magic Lore': 2, 'Thievery': 1, 'Alteration': 2 },
    gear: [['Chalk', 1], ['Torch', 1], ['Jaunt Book', 1], ['Animal Form Book', 1], ['Repair Book', 1], ['Take Shape Book', 1]] },
  { name: 'Village Watch', d: [6, 6], blurb: 'You kept a settlement safe.', two: ['Strength'], stamina: 9,
    trait: ['Armor', 'Stand Strong'],
    exp: { 'Athletics': 1, 'Search': 1, 'Stabbing': 1 },
    gear: [['Chain', 1], ['Lantern', 1], ['Light Armor', 1], ['Oil Flask', 1], ['Padlock', 1], ['Pike', 1], ['Whistle', 1]] }
];

/*
 * Inventory cards. st = stack size, sl = slots occupied, cat = category used for auto-arranging,
 * hands = hands needed to wield (Cumbersome / 2-slot), txt = condensed card text, gc = price.
 */
CROWS.ITEMS = {
  // ---- Weapons ----
  'Hammer': { cat: 'weapon', st: 2, sl: 1, gc: 10, wt: 'Bashing', txt: 'Melee 1/Ranged 5. Attack 2d10 + A or S. 12-16: 2 + A or S; 17+: 4 + A or S. Bashing, Light, Pummeling.' },
  'Mace': { cat: 'weapon', st: 1, sl: 1, gc: 12, wt: 'Bashing', txt: 'Melee 1. Attack 2d10 + S. 12-16: 3 + S; 17+: 6 + S. Bashing, Pummeling.' },
  'Flail': { cat: 'weapon', st: 1, sl: 2, gc: 15, wt: 'Bashing', txt: 'Melee 2. Attack 2d10 + S. 12-16: 3 + S; 17+: 6 + S. Bashing, Pummeling. Occupies 2 slots.' },
  'Maul': { cat: 'weapon', st: 1, sl: 2, gc: 15, wt: 'Bashing', txt: 'Melee 1. Attack 2d10 + S. 12-16: 4 + S; 17+: 8 + S. Bashing, Pummeling. Occupies 2 slots.' },
  'Handaxe': { cat: 'weapon', st: 2, sl: 1, gc: 10, wt: 'Chopping', txt: 'Melee 1/Ranged 5. Attack 2d10 + A or S. 12-16: 2 + A or S; 17+: 5 + A or S. Chopping, Light, Dismember.' },
  'Axe': { cat: 'weapon', st: 1, sl: 1, gc: 12, wt: 'Chopping', txt: 'Melee 1. Attack 2d10 + S. 12-16: 3 + S; 17+: 7 + S. Chopping, Dismember.' },
  'Halberd': { cat: 'weapon', st: 1, sl: 2, gc: 15, wt: 'Chopping', txt: 'Melee 2. Attack 2d10 + S. 12-16: 3 + S; 17+: 7 + S. Chopping, Dismember. Occupies 2 slots.' },
  'Greataxe': { cat: 'weapon', st: 1, sl: 2, gc: 15, wt: 'Chopping', txt: 'Melee 1. Attack 2d10 + S. 12-16: 4 + S; 17+: 9 + S. Chopping, Dismember. Occupies 2 slots.' },
  'Knife': { cat: 'weapon', st: 2, sl: 1, gc: 10, wt: 'Slashing', light: true, txt: 'Melee 1/Ranged 5. Attack 2d10 + A or S. 12-16: 2 + A or S; 17+: 4 + A or S. Slashing, Light, Disengage, Parry 2.' },
  'Sword': { cat: 'weapon', st: 1, sl: 1, gc: 12, wt: 'Slashing', txt: 'Melee 1. Attack 2d10 + S. 12-16: 3 + S; 17+: 6 + S. Slashing, Disengage, Parry 4.' },
  'Glaive': { cat: 'weapon', st: 1, sl: 2, gc: 15, wt: 'Slashing', txt: 'Melee 2. Attack 2d10 + S. 12-16: 3 + S; 17+: 6 + S. Slashing, Disengage, Parry 6. Occupies 2 slots.' },
  'Greatsword': { cat: 'weapon', st: 1, sl: 2, gc: 15, wt: 'Slashing', txt: 'Melee 1. Attack 2d10 + S. 12-16: 4 + S; 17+: 8 + S. Slashing, Disengage, Parry 6. Occupies 2 slots.' },
  'Stiletto': { cat: 'weapon', st: 2, sl: 1, gc: 10, wt: 'Stabbing', txt: 'Melee 1/Ranged 5. Attack 2d10 + A or S. 12-16: 2 + A or S; 17+: 5 + A or S. Stabbing, Light, Brutal.' },
  'Spear': { cat: 'weapon', st: 1, sl: 1, gc: 12, wt: 'Stabbing', txt: 'Melee 1. Attack 2d10 + S. 12-16: 3 + S; 17+: 7 + S. Stabbing, Brutal.' },
  'Pike': { cat: 'weapon', st: 1, sl: 2, gc: 15, wt: 'Stabbing', txt: 'Melee 2. Attack 2d10 + S. 12-16: 3 + S; 17+: 7 + S. Stabbing, Brutal. Occupies 2 slots.' },
  'Warpick': { cat: 'weapon', st: 1, sl: 2, gc: 15, wt: 'Stabbing', txt: 'Melee 1. Attack 2d10 + S. 12-16: 4 + S; 17+: 9 + S. Stabbing, Brutal. Occupies 2 slots.' },
  'Shortbow': { cat: 'weapon', st: 1, sl: 1, hands: 2, gc: 10, wt: 'Bow', txt: 'Ranged 10. Attack 2d10 + A. 12-16: 2 + A; 17+: 4 + A. Bow, Cumbersome (1 slot, but needs 2 hands to wield). Uses arrows.' },
  'Longbow': { cat: 'weapon', st: 1, sl: 2, gc: 12, wt: 'Bow', txt: 'Ranged 20. Attack 2d10 + A. 12-16: 3 + A; 17+: 6 + A. Bow. Occupies 2 slots. Uses arrows.' },
  'Crossbow': { cat: 'weapon', st: 1, sl: 2, gc: 15, wt: 'Bow', txt: 'Ranged 15. Attack 2d10 + A. 12-16: 4 + A; 17+: 8 + A. Bow, Reload. Occupies 2 slots. Uses bolts.' },
  'Quiver of 20 Arrows': { cat: 'ammo', st: 1, sl: 1, gc: 5, txt: 'Ammunition for shortbows and longbows. Ammo used in a ranged attack is destroyed.' },
  'Case of 20 Crossbow Bolts': { cat: 'ammo', st: 1, sl: 1, gc: 5, txt: 'Ammunition for crossbows.' },
  // ---- Armor ----
  'Light Armor': { cat: 'armor', st: 1, sl: 2, gc: 50, ad: 5, txt: 'Armor, AD 5. Occupies 2 slots. Worn from the backpack (one suit at a time; don only outside combat rounds).' },
  'Medium Armor': { cat: 'armor', st: 1, sl: 3, gc: 150, ad: 10, txt: 'Armor, AD 10. Occupies 3 slots. Worn from the backpack.' },
  'Heavy Armor': { cat: 'armor', st: 1, sl: 4, gc: 400, ad: 15, txt: 'Armor, AD 15. Occupies 4 slots. Worn from the backpack.' },
  'Shield': { cat: 'shield', st: 1, sl: 1, gc: 15, ad: 5, txt: 'Armor, AD 5. Only protects while wielded in a hand slot.' },
  // ---- Gear ----
  '11-Foot Pole': { cat: 'bulky', st: 1, sl: 2, gc: 5, txt: 'An 11-foot-long wooden pole. For poking. Also prodding! Occupies 2 slots.' },
  "Alchemist's Tools": { cat: 'tool', st: 1, sl: 1, gc: 15, txt: 'Required to make crafting rolls for alchemy items. Fine (500 gc): +1. Masterwork (1,000 gc): +2.' },
  'Alteration Stone': { cat: 'magic', st: 1, sl: 1, gc: 0, txt: 'Choose one benefit when you make the stone; the creature carrying it gains it: no need to eat or drink; no need to breathe; or the stone sheds light 5/5.' },
  'Animal Feed': { cat: 'food', st: 6, sl: 1, gc: 1, txt: "A day's worth of food for a pet. Must be consumed during a rest to get the benefit of resting." },
  'Ball Bearings': { cat: 'trap', st: 2, sl: 1, gc: 5, txt: 'A bag of 1,000. Maneuver: spread over a 2 x 2 area. Creatures entering make an Agility RR. <=11: prone and 4 dam; 12-16: prone; 17+: no effect.' },
  'Bear Trap': { cat: 'trap', st: 1, sl: 1, gc: 250, txt: 'Maneuver: set on the ground. A creature stepping on it takes 1d6 dam and, if Large or smaller, is grabbed. The trap has 10 Stamina.' },
  "Blacksmith's Tools": { cat: 'tool', st: 1, sl: 1, gc: 15, txt: 'Required to make crafting rolls for blacksmithing items. Fine (500 gc): +1. Masterwork (1,000 gc): +2.' },
  'Block & Tackle': { cat: 'tool', st: 1, sl: 1, gc: 100, txt: 'Set of 2 hooked pulleys that can lift up to 500 lbs. Rope sold separately.' },
  'Bucket': { cat: 'misc', st: 1, sl: 1, gc: 2, txt: 'Can hold up to 3 gallons of liquid ... also good for hiding your face!' },
  'Caltrops': { cat: 'trap', st: 2, sl: 1, gc: 5, txt: 'A bag of 1,000. Maneuver: spread over a 2 x 2 area. Creatures entering make an Agility RR. <=11: 4 dam and -2 speed until healed; 12-16: 2 dam; 17+: no effect.' },
  'Candle': { cat: 'light', st: 5, sl: 1, gc: 1, txt: 'UD: 1 (Useless; DT). Maneuver: Light 0/5.' },
  'Card Deck': { cat: 'misc', st: 5, sl: 1, gc: 1, txt: 'Standard deck of 54 playing cards, including 2 jokers.' },
  'Chain': { cat: 'misc', st: 1, sl: 1, gc: 5, txt: 'A 10-foot length of iron chain.' },
  'Chalk': { cat: 'misc', st: 5, sl: 1, gc: 1, txt: 'UD: 1 (Useless; Activate). Mark your way or leave messages on stone.' },
  'Coin Purse': { cat: 'purse', st: 1, sl: 1, gc: 1, txt: 'Holds up to 500 coins. (A slot holds 250 loose coins or 1 purse.)' },
  'Cold Weather Gear': { cat: 'misc', st: 1, sl: 1, gc: 10, txt: 'Survive cold snaps and blizzards. Counts as worn while in a backpack slot.' },
  'Compass': { cat: 'misc', st: 3, sl: 1, gc: 10, txt: 'Tests related to the guide travel role gain +1 while you carry it.' },
  "Cook's Utensils": { cat: 'tool', st: 1, sl: 1, gc: 15, txt: 'Required for some special rest activities (Camping trait tree).' },
  'Crowbar': { cat: 'tool', st: 1, sl: 1, gc: 10, txt: 'An iron bar used in prying. Fine (750 gc): +1 on tests using it. Masterwork (1,500 gc): +2.' },
  "Enchanter's Tools": { cat: 'tool', st: 1, sl: 1, gc: 15, txt: 'Required to make crafting rolls for enchanting items. Fine (500 gc): +1. Masterwork (1,000 gc): +2.' },
  'Grappling Hook': { cat: 'misc', st: 1, sl: 1, gc: 10, txt: 'Add to rope to create a 2-slot item. Makes hurling and securing rope easier.' },
  'Holy Symbol': { cat: 'misc', st: 2, sl: 1, gc: 15, txt: 'A symbol of your god. Can be worn in the neck slot, but isn\'t magic.' },
  'Journal': { cat: 'misc', st: 1, sl: 1, gc: 2, txt: "A bound journal of 200 blank pages. Don't worry, you'll fill them!" },
  'Ladder': { cat: 'bulky', st: 1, sl: 2, gc: 30, txt: 'Collapsible. Maneuver: the ladder expands 10 feet. Occupies 2 slots.' },
  'Lantern': { cat: 'light', st: 2, sl: 1, gc: 25, txt: 'UD: 2 (Refuel with oil; DT). Maneuver: Light 10/10.' },
  'Lockpick Set': { cat: 'tool', st: 1, sl: 1, gc: 25, txt: 'Without this, you take a bane on tests made to pick locks.' },
  'Lore Book': { cat: 'book', st: 1, sl: 1, gc: 50, txt: 'Study as a rest activity to gain 1 use of the related expertise until your next rest.' },
  'Lore Book (Historical Lore)': { cat: 'book', st: 1, sl: 1, gc: 50, txt: 'Historical Lore. Study as a rest activity to gain 1 use of that expertise until your next rest.' },
  'Lore Book (Monster Lore)': { cat: 'book', st: 1, sl: 1, gc: 50, txt: 'Monster Lore. Study as a rest activity to gain 1 use of that expertise until your next rest.' },
  'Lore Book (Nature Lore)': { cat: 'book', st: 1, sl: 1, gc: 50, txt: 'Nature Lore. Study as a rest activity to gain 1 use of that expertise until your next rest.' },
  'Lore Book (Magic Lore)': { cat: 'book', st: 1, sl: 1, gc: 50, txt: 'Magic Lore. Study as a rest activity to gain 1 use of that expertise until your next rest.' },
  'Magnifying Glass': { cat: 'misc', st: 2, sl: 1, gc: 100, txt: 'Better inspect the minute visual details of nearby creatures and objects.' },
  "Merchant's Scales": { cat: 'tool', st: 1, sl: 1, gc: 50, txt: 'Weigh Tiny objects and Tiny creatures that sit still.' },
  'Mirror': { cat: 'misc', st: 2, sl: 1, gc: 100, txt: 'A hand mirror, useful for looking around corners and at your own mug.' },
  'Musical Instrument (Lute)': { cat: 'tool', st: 1, sl: 1, gc: 100, txt: 'A portable instrument. To play it, it must occupy both your hand slots.' },
  'Net': { cat: 'misc', st: 1, sl: 1, gc: 5, txt: 'Hurl at a Medium or smaller creature as part of Grab: you gain an edge, they take a bane to break the grab. 5 Stamina.' },
  'Oil Flask': { cat: 'consumable', st: 2, sl: 1, gc: 5, txt: 'Maneuver: refuel lantern, or spread over 2 x 2 (Agility RR: <=11 prone; 12-16 lose 2 squares of movement). Flammable: burns 1d6 rounds, 1d6 dam.' },
  'Padlock': { cat: 'misc', st: 3, sl: 1, gc: 25, txt: 'Iron padlock. Includes a key.' },
  'Pitons': { cat: 'misc', st: 2, sl: 1, gc: 5, txt: 'Iron spikes hammered into stone to secure ropes. Come in multiples of 10.' },
  'Plague Mask': { cat: 'magic', st: 1, sl: 1, gc: 500, txt: 'Slot: Head. While worn, +2 bonus on Mind RRs to resist the Miasma.' },
  'Pot': { cat: 'misc', st: 1, sl: 1, gc: 5, txt: 'Iron pot for cooking, with a heavy lid.' },
  'Quill & Inkpot': { cat: 'misc', st: 5, sl: 1, gc: 5, txt: 'For writing stuff down!' },
  'Ration': { cat: 'food', st: 6, sl: 1, gc: 2, txt: "A day's worth of food. Eat 1 during a rest to avoid starvation and get the benefits of the rest." },
  'Hearty Ration': { cat: 'food', st: 6, sl: 1, gc: 2, txt: 'When you consume this ration during a rest, you remove 1 additional wound.' },
  'Rope': { cat: 'misc', st: 1, sl: 1, gc: 2, txt: '50 feet of rope. If secured, no test is required to climb.' },
  'Shovel': { cat: 'tool', st: 1, sl: 1, gc: 10, txt: 'Dig holes! Can make a decent crowbar in a pinch, but might break.' },
  'Soap': { cat: 'misc', st: 3, sl: 1, gc: 1, txt: 'UD: 1 (Useless; Activate). Clean, leave messages, whittle, or lubricate locks, tools, or your wrists.' },
  'Spyglass': { cat: 'misc', st: 2, sl: 1, gc: 100, txt: 'Makes things appear 3 times closer.' },
  'String': { cat: 'misc', st: 1, sl: 1, gc: 1, txt: '1,000 feet of string.' },
  'Surgical Kit': { cat: 'tool', st: 1, sl: 1, gc: 100, txt: 'UD: 1 (Useless; Activate). Use with Tend Wounds: the target loses 1 additional wound.' },
  'Tent': { cat: 'bulky', st: 1, sl: 2, gc: 100, txt: 'Waterproof canvas tent sleeps up to 4 humans. Wait out bad weather. Occupies 2 slots.' },
  'Torch': { cat: 'light', st: 2, sl: 1, gc: 2, txt: 'UD: 1 (Useless; DT). Maneuver: Light 5/5.' },
  'Whistle': { cat: 'misc', st: 5, sl: 1, gc: 5, txt: 'Maneuver: create a loud noise heard from 20 squares away.' },
  // ---- Alchemy ----
  'Acid Vial': { cat: 'consumable', st: 5, sl: 1, gc: 10, txt: 'Maneuver: pour to destroy up to 1 cubic foot of mundane matter. Action: ranged 5 attack using Agility. 12-16: 4 + A; 17+: 8 + A.' },
  'Strong Acid Vial': { cat: 'consumable', st: 5, sl: 1, gc: 250, txt: 'Maneuver: pour to destroy up to 5 cubic feet. Action: ranged 5 attack using Agility. 12-16: 7 + A; 17+: 14 + A.' },
  'Fire Bomb': { cat: 'consumable', st: 2, sl: 1, gc: 250, txt: 'Action: throw up to 10 squares; explodes in a 3 cube. Agility RR: <=11: 10 dam; 12-16: 5 dam; 17+: 0 dam.' },
  'Glue Pot': { cat: 'consumable', st: 2, sl: 1, gc: 125, txt: 'Maneuver: spread over 2 x 2. Creatures entering make a Strength RR. <=11: grabbed by the glue; 12-16: speed halved this turn; 17+: no effect.' },
  'Healing Potion': { cat: 'consumable', st: 5, sl: 1, gc: 100, txt: 'Maneuver: consume to regain 1d6 Stamina, or remove 1 wound if Stamina is already at maximum.' },
  'Poison Vial': { cat: 'consumable', st: 5, sl: 1, gc: 10, txt: 'Maneuver: apply to a weapon or 1 ammo. Next damage before DT end: Strength RR. <=11: 5 P dam and weakened; 12-16: 5 P dam; 17+: no effect.' },
  'Strong Poison': { cat: 'consumable', st: 5, sl: 1, gc: 250, txt: 'As poison vial, but 10 P dam (and weakened on <=11).' },
  'Rage Potion': { cat: 'consumable', st: 5, sl: 1, gc: 250, txt: 'Maneuver: consume to gain +5 AD and deal +2 damage with melee attacks. Lasts as long as you keep attacking creatures each round.' },
  'Smoke Bomb': { cat: 'consumable', st: 2, sl: 1, gc: 50, txt: 'Maneuver: throw up to 10 squares; creates a 3-cube of heavy concealment. Light concealment after d6 rounds, gone d6 rounds later.' },
  'Speed Potion': { cat: 'consumable', st: 5, sl: 1, gc: 100, txt: 'Maneuver: consume to increase your speed by 1. Duration: 1 UD.' },
  // ---- Magic items ----
  'Boom Wand': { cat: 'magic', st: 2, sl: 1, gc: 500, txt: 'UD 1 (Useless; Activate). Action: 5 cube of fire within 15 squares. Agility RR: <=11 10 dam; 12-16 5 dam; 17+ 0.' },
  'Hurling Wand': { cat: 'magic', st: 2, sl: 1, gc: 500, txt: 'UD 1 (Useless; Activate). Maneuver: target within 15 squares makes a Strength RR. <=11 vertical slide 10; 12-16 vertical slide 5; 17+ no effect.' },
  'Life Ring': { cat: 'magic', st: 10, sl: 1, gc: 500, txt: 'Slot: Ring. UD 1 (Rest; Activate). Maneuver: regain 1d6 Stamina, end a condition, or heal 1 wound.' },
  'Death Ring': { cat: 'magic', st: 10, sl: 1, gc: 1000, txt: 'Slot: Ring. UD 1 (Rest; Activate). Action: undead within 10 makes a M RR. <=11 teleports next to you and can counter; 12-16 you control it 1 round; 17+ until end of DT.' },
  'Minor Telekinesis Ring': { cat: 'magic', st: 10, sl: 1, gc: 500, txt: 'Slot: Ring. UD 1 (Rest; Activate). Action: vertically slide an unattended Small or smaller object within 10 squares up to 10 squares.' },
  'Necklace of Teeth': { cat: 'magic', st: 3, sl: 1, gc: 500, txt: 'Slot: Neck. While worn, your unarmed strikes deal +1 dam.' },
  'Whistle of Dog Summoning': { cat: 'magic', st: 5, sl: 1, gc: 500, txt: 'UD 1 (Rest; Activate). Action: summon a dog pet until end of DT or 0 Stamina.' },
  // ---- Spellbooks (Rank, Discipline, casting time) ----
  'Animal Form Book': { cat: 'spell', st: 1, sl: 1, gc: 250, txt: 'R0 Alteration, Maneuver. UD 1 (Rest; Activate). Self. Dur 1 UD. Gain the stats and form of an animal of max power <=11: 0; 12-16: 2; 17+: 4.' },
  'Repair Book': { cat: 'spell', st: 1, sl: 1, gc: 250, txt: 'R0 Alteration, Maneuver. UD 1 (Rest; Activate). Melee 1, 1 object. Object regains Stamina <=11: 1+M; 12-16: 4+M; 17+: 8+M.' },
  'Take Shape Book': { cat: 'spell', st: 1, sl: 1, gc: 250, txt: 'R0 Alteration, Maneuver. UD 1 (Rest; Activate). Self, Dur 1 UD. Look like a creature. <=11 no effect; 12-16 look only (size); 17+ gain size, speed, Stamina.' },
  'Minor Blessing Book': { cat: 'spell', st: 1, sl: 1, gc: 250, txt: 'R0 Benefaction, Action. UD 1 (Rest; Activate). Ranged 3. Targets become blessed: <=11: 0; 12-16: 1; 17+: 2 creatures.' },
  'Minor Healing Book': { cat: 'spell', st: 1, sl: 1, gc: 250, txt: 'R0 Benefaction, Maneuver. UD 1 (Rest; Activate). Melee 1, 1 creature. Regains Stamina <=11: 1+M; 12-16: 2+M; 17+: 4+M.' },
  'Minor Ward Book': { cat: 'spell', st: 1, sl: 1, gc: 250, txt: 'R0 Benefaction, Maneuver. UD 1 (Rest; Activate). Melee 1, 1 creature. Gains AD <=11: none; 12-16: 1+M; 17+: 3+M.' },
  'Jaunt Book': { cat: 'spell', st: 1, sl: 1, gc: 250, txt: 'R0 Conjuration, Maneuver. UD 1 (Rest; Activate). Self. Teleport <=11: no effect; 12-16: 5+M; 17+: 10+M squares.' },
  'Teleport Object Book': { cat: 'spell', st: 1, sl: 1, gc: 250, txt: 'R0 Conjuration, Maneuver. UD 1 (Rest; Activate). Ranged 10, 1 Tiny object. Teleport it <=11: no effect; 12-16: 5+M; 17+: 10+M squares (can land in an open hand).' },
  'Summon Object Book': { cat: 'spell', st: 1, sl: 1, gc: 250, txt: 'R0 Conjuration, Maneuver. UD 1 (Rest; Activate). Dur 1 UD. Create a mundane object in an open slot worth <=11: 10; 12-16: 50; 17+: 100 gc.' },
  'Create Water Book': { cat: 'spell', st: 1, sl: 1, gc: 250, txt: 'R0 Elemental, Maneuver. UD 1 (Rest; Activate). Ranged 10. Make water <=11: 1 gal; 12-16: 5 gal; 17+: 10 gal.' },
  'Fire Hands Book': { cat: 'spell', st: 1, sl: 1, gc: 250, atk: true, txt: 'R0 Elemental Attack. UD 1 (Rest; Activate). Melee 1. 12-16: 4+M; 17+: 8+M.' },
  'Fire Lance Book': { cat: 'spell', st: 1, sl: 1, gc: 250, atk: true, txt: 'R0 Elemental Attack. UD 1 (Rest; Activate). Ranged 10. 12-16: 2+M; 17+: 4+M.' },
  'Spark Book': { cat: 'spell', st: 1, sl: 1, gc: 250, atk: true, txt: 'R0 Elemental Attack. UD 1 (Rest; Activate). Ranged 5, 2 targets. 12-16: 1+M; 17+: 3+M.' },
  'Stream Book': { cat: 'spell', st: 1, sl: 1, gc: 250, atk: true, txt: 'R0 Elemental Attack. UD 1 (Rest; Activate). Line 5 x 1 within 1, all creatures. <=11: 0 dam; 12-16: 2+M; 17+: 4+M.' },
  'Thunder Book': { cat: 'spell', st: 1, sl: 1, gc: 250, atk: true, txt: 'R0 Elemental Attack. UD 1 (Rest; Activate). Ranged 5. 12-16: 2+M, push 1; 17+: 4+M, push 2.' },
  'Cacophony Book': { cat: 'spell', st: 1, sl: 1, gc: 250, txt: 'R0 Illusion, Maneuver. UD 1 (Rest; Activate). Ranged 10, Dur 1 UD. Phantom noise heard up to <=11: no effect; 12-16: 5+M; 17+: 10+M squares.' },
  'Light Book': { cat: 'spell', st: 1, sl: 1, gc: 250, txt: 'R0 Illusion, Maneuver. UD 1 (Rest; Activate). Melee 1, 1 object, Dur 1 UD. Object sheds light <=11: 0/5; 12-16: 5/5; 17+: 10/10.' },
  'Minor Phantasm Book': { cat: 'spell', st: 1, sl: 1, gc: 250, txt: 'R0 Illusion, Maneuver. UD 1 (Rest; Activate). Ranged 10, Dur 1 UD. Silent phantom image up to <=11: Tiny; 12-16: Small; 17+: Medium.' },
  'Bone Capture Book': { cat: 'spell', st: 1, sl: 1, gc: 250, atk: true, txt: 'R0 Necromancy Attack. UD 1 (Rest; Activate). Ranged 5, 1 creature. 12-16: 2+M; 17+: 4+M and prone.' },
  'Minor Curse Book': { cat: 'spell', st: 1, sl: 1, gc: 250, atk: true, txt: 'R0 Necromancy, Action. UD 1 (Rest; Activate). Melee 1, 1 creature. <=11: no effect; 12-16: 2+M dam; 17+: 4+M dam and weakened.' },
  'Monster Sense Book': { cat: 'spell', st: 1, sl: 1, gc: 250, txt: "R0 Necromancy, Maneuver. UD 1 (Rest; Activate). Self, Dur 1 UD. Know locations of non-human, non-animal creatures within <=11: 1; 12-16: 5; 17+: 10 squares, through walls." },
  'Wound Closure Book': { cat: 'spell', st: 1, sl: 1, gc: 500, txt: 'R0 Benefaction, Action. UD 1 (Rest; Activate). Melee 1, 1 creature. Heals wounds <=11: 0; 12-16: 1; 17+: 2.' },
  'Shrink Book': { cat: 'spell', st: 1, sl: 1, gc: 500, txt: 'R1 Alteration, Maneuver. UD 1 (Rest; Activate). Melee 1, 1 creature, Dur 1 UD. Size categories / weapon dmg: <=11 0/0; 12-16 1/-2; 17+ 2/-4.' },
  'Stubborn Object Book': { cat: 'spell', st: 1, sl: 1, gc: 500, txt: 'R1 Alteration, Maneuver. UD 1 (Rest; Activate). Melee 1, 1 object, Dur 1 UD. Fixed in space unless moved by Strength >= <=11: 2; 12-16: 3; 17+: 4.' },
  'Group Healing Book': { cat: 'spell', st: 1, sl: 1, gc: 500, txt: 'R1 Benefaction, Maneuver. UD 1 (Rest; Activate). Ranged 3, 3 creatures. Regain Stamina <=11: 1+M; 12-16: 2+M; 17+: 4+M.' },
  'Corrupt Book': { cat: 'spell', st: 1, sl: 1, gc: 500, atk: true, txt: 'R1 Necromancy Attack. UD 1 (Rest; Activate). Ranged 5, 1 creature. 12-16: 4+M dam; 17+: 8+M dam and vulnerable.' },
  'Deadspeech Book': { cat: 'spell', st: 1, sl: 1, gc: 500, txt: 'R1 Necromancy, Maneuver. UD 1 (Rest; Activate). Melee 1, 1 corpse, Dur end of DT. It honestly answers <=11: 1; 12-16: 3; 17+: 5 questions.' }
};

/* Pets granted by backgrounds (Ref Book bestiary; playtest stat blocks). */
CROWS.PETS = {
  'Dog': 'Dog (Medium animal, Power 2). Stamina 9, Speed 7, Slots 1. A 1, M -2, S 0. Bite (+1) Melee 1: 12-16 2 dam, 17+ 4 dam. No dim light penalty.',
  'Goat': 'Goat (Medium animal, Power 2). Stamina 8, Speed 5, Slots 2. A 0, M -2, S 1. Gore (+1) Melee 1: 12-16 2 dam, 17+ 4 dam. No dim light penalty.',
  'Riding Horse': 'Riding Horse (Large animal, Power 5). Stamina 15, Speed 10, Slots 10. A 2, M -2, S 2. Kick (+2) Melee 1: 12-16 3 dam, 17+ 6 dam. Rideable (rider occupies 6 of its slots). Eats 2 feed per rest.'
};

/* Expertise & Stamina Advancement: [TXP, max uses]. After 30,000: every 30,000 more, max 4. */
CROWS.ES_ADV = [[100, 2], [500, 2], [1250, 2], [2250, 2], [3500, 2], [5000, 3], [10000, 3], [20000, 4], [30000, 4]];
/* Characteristics Advancement: 5,000, 15,000, 30,000, then every 30,000 after. */
CROWS.CHAR_ADV = [5000, 15000, 30000];

CROWS.CONNECTION_BENEFITS = [
  ['Animal Lover', 'Looks after and feeds your pets in the village for free. Animals resting with them heal 2 additional wounds (3 if Prosperity 6+).'],
  ['Caretaker', 'You can rest in their home in the village and heal 2 additional wounds (3 if Prosperity 6+).'],
  ['Concerned', 'Once per cycle when you leave the village, they give you 1 torch.'],
  ['Crafty', 'When you make a crafting roll in the village, you gain a +2 bonus.'],
  ['Foodie', 'Once per cycle when you leave the village, they give you rations equal to half the Prosperity (min 1).'],
  ['Magic Enthusiast', 'Each day they can identify magic items equal to Prosperity (min 1) and share their properties.'],
  ['Money Bags', 'Will lend you up to 100 x Prosperity gc (min 100 gc); no new loan until the last is repaid.'],
  ['Monster Collector', 'Trades 1 monster part of a specific type for 5 monster parts of another type.'],
  ['Rival', 'A rival crow. Once per cycle you bet on whose adventure pays more; roll any die on return (even: you win). Loser pays 50 gc.'],
  ['Smarty Pants', 'Researches one question at a time in the village; if answerable, the answer comes 1 day later.']
];

CROWS.STARTING_INSTITUTIONS = ['Alchemist', 'Auction House', 'Barracks', 'Beacon', 'Bookseller', 'Enchanter', 'Stables'];

/* Traits granting an extra (restricted) belt slot. */
CROWS.EXTRA_BELT_TRAITS = {
  'Alchemy Belt': 'alchemy items only', 'Bashing Holster': 'bashing weapons only',
  'Chopping Holster': 'chopping weapons only', 'Stabbing Holster': 'stabbing weapons only',
  'Portal Pocket': 'extradimensional; only you can access'
};

CROWS.NAME_IDEAS = {
  first: ['Aldric', 'Bryn', 'Corra', 'Dunstan', 'Edda', 'Fenwick', 'Gilda', 'Hollis', 'Isolde', 'Jory', 'Kestrel', 'Lark', 'Marek', 'Nell', 'Osric', 'Petra', 'Quill', 'Rook', 'Sabine', 'Tamsin', 'Ulric', 'Vesna', 'Wren', 'Yorick', 'Zora', 'Mags', 'Brannoc', 'Tilde', 'Hobb', 'Ysolde'],
  last: ['Ashdown', 'Blackmoor', 'Crowley', 'Dunmere', 'Fairweather', 'Grimsby', 'Hollowell', 'Ironside', 'Kettle', 'Larkspur', 'Mudd', 'Nettles', 'Oakes', 'Pike', 'Quarry', 'Ravensworth', 'Stitch', 'Thorne', 'Underhill', 'Vane', 'Whitlock', 'Yarrow', 'Barrow', 'Candlewick'],
  feature: ['a jagged scar across one cheek', 'always smells faintly of pipe smoke', 'a booming, theatrical voice', 'mismatched eyes (one green, one grey)', 'hums tuneless songs when nervous', 'a crow tattoo on the back of one hand', 'missing two fingers on the left hand', 'wears a battered wide-brimmed hat', 'laughs at the worst possible moments', 'counts coins obsessively', 'speaks in a hoarse whisper', 'collects teeth from fallen monsters', 'wildly superstitious about the number three', 'bright copper hair braided with bones', 'never takes off a moth-eaten red scarf', 'a nervous stutter that vanishes in a fight']
};
