/* Trait trees extracted from Crows Characters Book (Playtest 2). Generated by build/extract_traits. */
var CROWS_TRAIT_TREES = [
{
"tree": "Alchemy",
"sub": "For creating and using acid, poisons, potions, and bombs",
"traits": [
{
"n": "Midnight Oil",
"r": 0,
"c": 0,
"x": 500,
"d": "When you work on crafting an alchemy item as part of the Craft Equipment rest activity, you can make two crafting rolls for the item or make a second crafting roll for a different alchemy item."
},
{
"n": "Alchemy Epiphany",
"r": 1,
"c": 0,
"x": 1000,
"d": "When you make a crafting roll for an alchemy item, you get a crit when the dice without modifiers equal 18, 19, or 20."
},
{
"n": "Eschew Ingredients",
"r": 2,
"c": 0,
"x": 1500,
"d": "You can ignore the material requirements for crafting an alchemy item if the item's crafting goal is 100 or lower."
},
{
"n": "Two for One",
"r": 3,
"c": 0,
"x": 2000,
"d": "When you finishing crafting an alchemy item, you craft two of the item instead of one."
},
{
"n": "It Burns",
"r": 0,
"c": 1,
"x": 500,
"d": "Acids and poisons you craft deal additional damage equal to twice your Mind. Bombs you craft deal additional damage equal to your Mind."
},
{
"n": "Big Boom",
"r": 1,
"c": 1,
"x": 1000,
"d": "Bombs you craft have the size of the cube they effect increased by 1."
},
{
"n": "You In Particular",
"r": 2,
"c": 1,
"x": 1500,
"d": "When you use a bomb, choose one creature who must make the RR against its effects. That creature takes -2 penalty to the RR against the bomb."
},
{
"n": "Don't Waste a Drop",
"r": 3,
"c": 1,
"x": 2000,
"d": "You can use an acid or a poison twice before it is consumed."
},
{
"n": "Potent Potion",
"r": 0,
"c": 2,
"x": 500,
"d": "Healing potions you craft restore additional Stamina equal to your Mind or remove 1 additional wound if the drinker is already at full Stamina."
},
{
"n": "Lasting Brew",
"r": 1,
"c": 2,
"x": 1000,
"d": "Potions and poisons you craft that have a duration listed in UD gain 1 additional UD."
},
{
"n": "Potion to Gas",
"r": 2,
"c": 2,
"x": 1500,
"d": "As an action, you can turn a potion you carry into a gas. The potion is immediately consumed and two creatures of your choice within 1 square of you, including you, are affected as if they drank the potion."
},
{
"n": "Alchemy Belt",
"r": 3,
"c": 2,
"x": 2000,
"d": "You gain an additional belt slot that can only be used to hold alchemy items."
}
],
"edges": [
[
[
0,
0
],
[
1,
0
]
],
[
[
0,
1
],
[
1,
1
]
],
[
[
0,
1
],
[
1,
2
]
],
[
[
0,
2
],
[
1,
1
]
],
[
[
0,
2
],
[
1,
2
]
],
[
[
1,
0
],
[
2,
0
]
],
[
[
1,
1
],
[
2,
1
]
],
[
[
1,
1
],
[
2,
2
]
],
[
[
1,
2
],
[
2,
1
]
],
[
[
1,
2
],
[
2,
2
]
],
[
[
2,
0
],
[
3,
0
]
],
[
[
2,
1
],
[
3,
1
]
],
[
[
2,
2
],
[
3,
2
]
]
]
},
{
"tree": "Alteration",
"sub": "For maximal use of alteration spells",
"traits": [
{
"n": "Lasting Alteration",
"r": 0,
"c": 0,
"x": 500,
"d": "When you cast an alteration spell with a duration listed in UD, add an additional 1 UD to the duration."
},
{
"n": "Alteration Mastery",
"r": 1,
"c": 0,
"x": 1000,
"d": "Non-doom tier 1 results of rank 0 and 1 alteration spells you cast don't add to the chaos count. Your alteration spells of rank 2 and higher are treated as 2 ranks lower when they trigger a backlash."
},
{
"n": "Improved Animal",
"r": 2,
"c": 0,
"x": 1500,
"d": "When you cast an alteration spell that allows you to turn into an animal, you can turn into an animal with power equal to what the spell says plus your Mind."
},
{
"n": "Split Alteration",
"r": 3,
"c": 0,
"x": 2000,
"d": "When you cast an alteration spell that has a target of 1 creature, object, ally, enemy, or target, you can target one additional qualifying target."
},
{
"n": "Grow Scales",
"r": 0,
"c": 1,
"x": 500,
"d": "When you cast an alteration spell, you can harness the magic to grow temporary scales on your body and gain AD equal to your Mind. The AD granted by this trait disappears at the end of a rest."
},
{
"n": "Hooves",
"r": 1,
"c": 1,
"x": 1000,
"d": "When you cast an alteration spell, you can harness the magic to change your feet into powerful hooves until the end of the DT. While you have these hooves, your speed increase by your Mind."
},
{
"n": "Horns",
"r": 2,
"c": 1,
"x": 1500,
"d": "When you cast an alteration spell, you can harness the magic to grow horns from your head that last until the end of the DT. You can make an unarmed attack with the horns as a maneuver."
},
{
"n": "Wings",
"r": 3,
"c": 1,
"x": 2000,
"d": "When you cast an alteration spell, you can harness the magic to grow wings that last until the end of the DT. While you have these wings, you gain a flying speed equal to your speed."
},
{
"n": "Alteration Stone",
"r": 0,
"c": 2,
"x": 500,
"d": "As a rest activity, you can create an alteration stone (which has an equipment card). This stone disappears if you create a new one."
},
{
"n": "Morphing Stone",
"r": 1,
"c": 2,
"x": 1000,
"d": "A creature who holds the stone can use a maneuver to change it into the shape of a mace, maul, flail, or back to its original form. The stone gains the stats of its weapon form while retaining its own stats."
},
{
"n": "Movement Stone",
"r": 2,
"c": 2,
"x": 1500,
"d": "Add the following benefits to those your stone can confer: •\tYou can breathe underwater and gain a swimming speed equal to your speed. •\tYou gain a climbing speed equal to your speed."
},
{
"n": "Spell Stone",
"r": 3,
"c": 2,
"x": 2000,
"d": "Choose up to three alteration spellbooks in your possession. The stone absorbs and destroys those books. A creature wielding the stone has those spellbooks equipped. The stone can only hold three spells."
}
],
"edges": [
[
[
0,
0
],
[
1,
0
]
],
[
[
0,
1
],
[
1,
1
]
],
[
[
0,
2
],
[
1,
2
]
],
[
[
1,
0
],
[
2,
0
]
],
[
[
1,
1
],
[
2,
1
]
],
[
[
1,
2
],
[
2,
2
]
],
[
[
2,
0
],
[
3,
0
]
],
[
[
2,
0
],
[
3,
1
]
],
[
[
2,
1
],
[
3,
0
]
],
[
[
2,
1
],
[
3,
1
]
],
[
[
2,
2
],
[
3,
2
]
]
]
},
{
"tree": "Archery",
"sub": "For mastery of bows",
"traits": [
{
"n": "Point Blank",
"r": 0,
"c": 0,
"x": 500,
"d": "When you make a ranged attack with a bow, you don't suffer the -1 penalty for having an enemy within 1 square of you."
},
{
"n": "Aim",
"r": 1,
"c": 0,
"x": 1000,
"d": "You can use a maneuver to aim while you have a bow weapon equipped. If you make an attack with that weapon before the end of this turn, the attack gains a +1 bonus."
},
{
"n": "Walls Can't Save You",
"r": 2,
"c": 0,
"x": 1500,
"d": "Attacks you make with bows don't suffer a penalty for the target having cover."
},
{
"n": "Split Shot",
"r": 3,
"c": 0,
"x": 2000,
"d": "When you make an attack with a bow, you can use twice as much ammunition and select two targets within range for the attack."
},
{
"n": "Range Finder",
"r": 0,
"c": 1,
"x": 500,
"d": "While you wield a bow weapon, it's range increases by 2 squares. This bonus stacks with Greater Range."
},
{
"n": "Greater Range",
"r": 1,
"c": 1,
"x": 1000,
"d": "While you wield a bow weapon, it's range increases by 2 squares. This bonus stacks with Range Finder."
},
{
"n": "Shot in the Dark",
"r": 2,
"c": 1,
"x": 1500,
"d": "Attacks you make with bows don't suffer a penalty for the target being in dim light or similar concealment, and they only suffer a -2 penalty against target in darkness or similar concealment."
},
{
"n": "Careful Shot",
"r": 3,
"c": 1,
"x": 2000,
"d": "When you get a non-doom tier 1 result on an attack made with a bow, you don't hit an ally within 1 square of the target."
},
{
"n": "Prone Position",
"r": 0,
"c": 2,
"x": 500,
"d": "If you are prone, you gain a +1 bonus on attacks made with crossbows."
},
{
"n": "Scrap Arrows",
"r": 1,
"c": 2,
"x": 1000,
"d": "As a rest activity, you can turn sticks and scraps of nearby wood into arrows and gain 2d6 arrows when you finish the rest."
},
{
"n": "Double Tap",
"r": 2,
"c": 2,
"x": 1500,
"d": "When you make an attack with a bow, you can use two pieces of ammunition per target. If the attack hits, it deals additional damage equal to your Agility."
},
{
"n": "Double Quiver",
"r": 3,
"c": 2,
"x": 2000,
"d": "You can hold up to 40 arrows in one quiver and it takes up only 1 slot."
}
],
"edges": [
[
[
0,
0
],
[
1,
0
]
],
[
[
0,
0
],
[
1,
1
]
],
[
[
0,
0
],
[
1,
2
]
],
[
[
0,
1
],
[
1,
0
]
],
[
[
0,
1
],
[
1,
1
]
],
[
[
0,
1
],
[
1,
2
]
],
[
[
0,
2
],
[
1,
0
]
],
[
[
0,
2
],
[
1,
1
]
],
[
[
0,
2
],
[
1,
2
]
],
[
[
1,
0
],
[
2,
0
]
],
[
[
1,
0
],
[
2,
1
]
],
[
[
1,
0
],
[
2,
2
]
],
[
[
1,
1
],
[
2,
0
]
],
[
[
1,
1
],
[
2,
1
]
],
[
[
1,
1
],
[
2,
2
]
],
[
[
1,
2
],
[
2,
0
]
],
[
[
1,
2
],
[
2,
1
]
],
[
[
1,
2
],
[
2,
2
]
],
[
[
2,
0
],
[
3,
0
]
],
[
[
2,
1
],
[
3,
1
]
],
[
[
2,
2
],
[
3,
2
]
]
]
},
{
"tree": "Armor",
"sub": "For getting the most out of protective wear",
"traits": [
{
"n": "Interposing Arm",
"r": 0,
"c": 0,
"x": 500,
"d": "When you wield a shield with at least 1 AD and a creature makes a weapon attack against a creature adjacent to you, you can use your reaction to cause the damage to apply your shield before the target."
},
{
"n": "Hurl Shield",
"r": 1,
"c": 0,
"x": 1000,
"d": "You can make a ranged weapon attack with your shield. This attack is a Strength test that is ranged 5 and deals 3 + S damage on a tier 2 result and 6 + S damage on a tier 3 result."
},
{
"n": "Wall of Protection",
"r": 2,
"c": 0,
"x": 1500,
"d": "While you have a shield equipped, you gain a +1 bonus on Agility RRs. When you make an Agility RR while wielding a shield, you can use a reaction to grant a +1 bonus to adjacent allies on the same RR."
},
{
"n": "Shield Bash",
"r": 3,
"c": 0,
"x": 2000,
"d": "When get a tier 3 result on the Knockback maneuver and force move the target while you have a shield equipped, the target is also knocked prone."
},
{
"n": "Stalwart",
"r": 0,
"c": 1,
"x": 500,
"d": "While wearing armor, the distance you can be force moved is reduced by 1, and you can't be knocked prone by tier 1 and 2 attack results or by tier 2 and 3 RR results."
},
{
"n": "Sacrifice Armor",
"r": 1,
"c": 1,
"x": 1000,
"d": "When an attack reduces armor you wear or a shield you wield to 0 AD and there is still damage left, you can reduce the remaining damage to 0. If you do, the armor reduced to 0 AD is destroyed."
},
{
"n": "Immovable",
"r": 2,
"c": 1,
"x": 1500,
"d": "Creatures of your size can't force move you or knock you prone with mundane attacks or the Knockback maneuver while you wear heavy armor."
},
{
"n": "Second Skin",
"r": 3,
"c": 1,
"x": 2000,
"d": "Armor you wear occupies 1 fewer slots."
},
{
"n": "Stand Strong",
"r": 0,
"c": 2,
"x": 500,
"d": "While you wear armor, you gain a +1 bonus on Strength RRs."
},
{
"n": "Headgear",
"r": 1,
"c": 2,
"x": 1000,
"d": "While you wear armor or a magic item in your head slot, you gain a +1 bonus on Mind RRs."
},
{
"n": "Jury-Rig Repairs",
"r": 2,
"c": 2,
"x": 1500,
"d": "You can quickly repair a piece of armor while you are not in combat, restoring 1d6 AD to it. You can't use this trait again until you finish a rest. This trait stacks with Emergency Repairs from the Blacksmithing tree."
},
{
"n": "Pierce This",
"r": 3,
"c": 2,
"x": 2000,
"d": "When you take piercing damage you can turn it into regular damage (no action required). Once you use this trait, you can't use it again until you finish a rest."
}
],
"edges": [
[
[
0,
0
],
[
1,
0
]
],
[
[
0,
1
],
[
1,
1
]
],
[
[
0,
1
],
[
1,
2
]
],
[
[
0,
2
],
[
1,
1
]
],
[
[
0,
2
],
[
1,
2
]
],
[
[
1,
0
],
[
2,
0
]
],
[
[
1,
1
],
[
2,
1
]
],
[
[
1,
2
],
[
2,
2
]
],
[
[
2,
0
],
[
3,
0
]
],
[
[
2,
0
],
[
3,
1
]
],
[
[
2,
0
],
[
3,
2
]
],
[
[
2,
1
],
[
3,
0
]
],
[
[
2,
1
],
[
3,
1
]
],
[
[
2,
1
],
[
3,
2
]
],
[
[
2,
2
],
[
3,
0
]
],
[
[
2,
2
],
[
3,
1
]
],
[
[
2,
2
],
[
3,
2
]
]
]
},
{
"tree": "Bashing",
"sub": "For mastery of hammers, maces, mauls, and flails",
"traits": [
{
"n": "Push 'Em Back",
"r": 0,
"c": 0,
"x": 500,
"d": "When you get a tier 3 result on an attack with a bashing and pummeling weapon, you push the target 1 additional square. This trait stacks with Further Back."
},
{
"n": "Further Back",
"r": 1,
"c": 0,
"x": 1000,
"d": "When you get a tier 3 result on an attack with a bashing and pummeling weapon, you push the target 1 additional square. This trait stacks with Push 'Em Back."
},
{
"n": "Collision Damage",
"r": 2,
"c": 0,
"x": 1500,
"d": "When you force move a creature into an object with a bashing weapon attack, the creature takes additional damage equal to the forced movement remaining when they collide."
},
{
"n": "Knock 'Em Together",
"r": 3,
"c": 0,
"x": 2000,
"d": "When you force move a creature into another with a bashing weapon attack, both creatures take damage equal to the forced movement remaining when they collide."
},
{
"n": "Destructive",
"r": 0,
"c": 1,
"x": 500,
"d": "You deal double damage to objects with bashing weapon attacks."
},
{
"n": "Big Ain't Nothing",
"r": 1,
"c": 1,
"x": 1000,
"d": "You can force move and knock prone creatures one size category larger than you and smaller with bashing weapon attacks."
},
{
"n": "Bashing Crit",
"r": 2,
"c": 1,
"x": 1500,
"d": "You score a crit on bashing weapon attacks when the dice without modifiers equal 18, 19, or 20."
},
{
"n": "Bashing Holster",
"r": 3,
"c": 1,
"x": 2000,
"d": "You gain an additional belt slot that can only hold bashing weapons."
},
{
"n": "Tripping Counter",
"r": 0,
"c": 2,
"x": 500,
"d": "When you counter with a bashing weapon against a creature who got a doom result on the triggering attack, you knock the target prone regardless of their size."
},
{
"n": "Piledriver",
"r": 1,
"c": 2,
"x": 1000,
"d": "When you knock a creature prone with a bashing weapon attack, you deal additional damage to them equal to your Strength."
},
{
"n": "Bone Breaker",
"r": 2,
"c": 2,
"x": 1500,
"d": "When you hit a grappled, prone, vulenarble, or weakened with a bashing weapon attack, you deal additional damage equal to your Strength."
},
{
"n": "Down You Go",
"r": 3,
"c": 2,
"x": 2000,
"d": "When you get a tier 3 result on a bashing weapon attack that results in the target being pushed, you can knock the target prone instead of pushing them."
}
],
"edges": [
[
[
0,
0
],
[
1,
0
]
],
[
[
0,
0
],
[
1,
1
]
],
[
[
0,
0
],
[
1,
2
]
],
[
[
0,
1
],
[
1,
0
]
],
[
[
0,
1
],
[
1,
1
]
],
[
[
0,
1
],
[
1,
2
]
],
[
[
0,
2
],
[
1,
0
]
],
[
[
0,
2
],
[
1,
1
]
],
[
[
0,
2
],
[
1,
2
]
],
[
[
1,
0
],
[
2,
0
]
],
[
[
1,
0
],
[
2,
1
]
],
[
[
1,
0
],
[
2,
2
]
],
[
[
1,
1
],
[
2,
0
]
],
[
[
1,
1
],
[
2,
1
]
],
[
[
1,
1
],
[
2,
2
]
],
[
[
1,
2
],
[
2,
0
]
],
[
[
1,
2
],
[
2,
1
]
],
[
[
1,
2
],
[
2,
2
]
],
[
[
2,
0
],
[
3,
0
]
],
[
[
2,
0
],
[
3,
1
]
],
[
[
2,
0
],
[
3,
2
]
],
[
[
2,
1
],
[
3,
0
]
],
[
[
2,
1
],
[
3,
1
]
],
[
[
2,
1
],
[
3,
2
]
],
[
[
2,
2
],
[
3,
0
]
],
[
[
2,
2
],
[
3,
1
]
],
[
[
2,
2
],
[
3,
2
]
]
]
},
{
"tree": "Benefaction",
"sub": "For maximum use of benefaction spells",
"traits": [
{
"n": "Lasting Benefaction",
"r": 0,
"c": 0,
"x": 500,
"d": "When you cast an benefaction spell with a duration listed in UD, add an additional 1 UD to the duration."
},
{
"n": "Benefaction Mastery",
"r": 1,
"c": 0,
"x": 1000,
"d": "Non-doom tier 1 results of rank 0 and 1 benefaction spells you cast don't add to the chaos count. Your benefaction spells of rank 2 and higher are treated as 2 ranks lower when they trigger a backlash."
},
{
"n": "Ranged Benefaction",
"r": 2,
"c": 0,
"x": 1500,
"d": "When you cast a benefaction spell with a range of Melee 1, you can change it to Ranged 5."
},
{
"n": "Split Benefaction",
"r": 3,
"c": 0,
"x": 2000,
"d": "When you cast an benefaction spell that has a target of 1 creature, object, ally, enemy, or target, you can target one additional qualifying target."
},
{
"n": "Enhanced Healing",
"r": 0,
"c": 1,
"x": 500,
"d": "When you cast a benefaction spell that restores Stamina to a target, the target regains additional Stamina equal to your Mind."
},
{
"n": "Many Blessings",
"r": 1,
"c": 1,
"x": 1000,
"d": "When you cast a benefaction spell that makes the spell's target blessed, you can become blessed as well. You can use this trait a number of times equal to your Mind, regaining all uses when you finish a rest."
},
{
"n": "Some For Me",
"r": 2,
"c": 1,
"x": 1500,
"d": "When you cast a benefaction spell that restores Stamina for another creature or removes at least 1 of their wounds, you regain Stamina equal to your Mind plus the spell's rank."
},
{
"n": "Stitching Magic",
"r": 3,
"c": 1,
"x": 2000,
"d": "When you cast a benefaction spell that makes the spell's target lose at least 1 wound, they lose 1 additional wound."
},
{
"n": "First Responder",
"r": 0,
"c": 2,
"x": 500,
"d": "When you have a benefaction spell that can restore Stamina to a creature equipped and a creature within the spell's range take damage, you can use your reaction to cast the spell, targeting that creature."
},
{
"n": "Benefaction Ward",
"r": 1,
"c": 2,
"x": 1000,
"d": "When you cast a benefaction spell, you can harness the magic to ward a creature within 5 squares who gains AD equal to your Mind. The AD granted by this trait disappears at the end of a rest."
},
{
"n": "Blessed Benefaction",
"r": 2,
"c": 2,
"x": 1500,
"d": "When you cast a benefaction spell, you harness the magic to make a creature within 5 squares of you blessed."
},
{
"n": "Burn Blessings",
"r": 3,
"c": 2,
"x": 2000,
"d": "When you cast a benefaction spell on a blessed target, you can remove the blessed condition from them. The target regains 1d6 Stamina or removes 1 wound for each level removed (your choice)."
}
],
"edges": [
[
[
0,
0
],
[
1,
0
]
],
[
[
0,
0
],
[
1,
1
]
],
[
[
0,
0
],
[
1,
2
]
],
[
[
0,
1
],
[
1,
0
]
],
[
[
0,
1
],
[
1,
1
]
],
[
[
0,
1
],
[
1,
2
]
],
[
[
0,
2
],
[
1,
0
]
],
[
[
0,
2
],
[
1,
1
]
],
[
[
0,
2
],
[
1,
2
]
],
[
[
1,
0
],
[
2,
0
]
],
[
[
1,
1
],
[
2,
1
]
],
[
[
1,
1
],
[
2,
2
]
],
[
[
1,
2
],
[
2,
1
]
],
[
[
1,
2
],
[
2,
2
]
],
[
[
2,
0
],
[
3,
0
]
],
[
[
2,
0
],
[
3,
1
]
],
[
[
2,
1
],
[
3,
0
]
],
[
[
2,
1
],
[
3,
1
]
],
[
[
2,
2
],
[
3,
2
]
]
]
},
{
"tree": "Blacksmithing",
"sub": "For creating armor and weapons",
"traits": [
{
"n": "Double Duty",
"r": 0,
"c": 0,
"x": 500,
"d": "When you work on crafting a blacksmithing item as part of the Craft Equipment rest activity, you can make two crafting rolls for the item or make a second crafting roll for a different blacksmithing item."
},
{
"n": "Smithing Epiphany",
"r": 1,
"c": 0,
"x": 1000,
"d": "When you make a crafting roll for an blacksmithing item, you get a crit when the dice without modifiers equal 18, 19, or 20."
},
{
"n": "Made with Spirit",
"r": 2,
"c": 0,
"x": 1500,
"d": "You can ignore the material requirements for crafting a blacksmithing item if the item's crafting goal is 100 or lower."
},
{
"n": "No Waste",
"r": 3,
"c": 0,
"x": 2000,
"d": "When you craft a blacksmithing item, you only use half the prerequisite materials required."
},
{
"n": "Armor Expert",
"r": 0,
"c": 1,
"x": 500,
"d": "When you make a crafting roll for an armor item, double the result to determine the number of crafting points added to the project."
},
{
"n": "Repair, Repair",
"r": 1,
"c": 1,
"x": 1000,
"d": "When you take the Repair Armor rest activity, you can choose up to two pieces of armor and restore their AD instead of one."
},
{
"n": "Emergency Repairs",
"r": 2,
"c": 1,
"x": 1500,
"d": "You can quickly repair a piece of armor while you are not in combat, restoring 1d6 AD to it. You can't use this trait again until you finish a rest. This trait stacks with Jury-Rig Repairs from the Armor tree."
},
{
"n": "Enchant Armor",
"r": 3,
"c": 1,
"x": 2000,
"d": "You can use your blacksmith's tools as enchanter's tools and your number of uses in the Blacksmithing expertise in place of Enchantment when crafting magic armor."
},
{
"n": "Weapon Expert",
"r": 0,
"c": 2,
"x": 500,
"d": "When you make a crafting roll for a weapon item, double the result to determine the number of crafting points added to the project."
},
{
"n": "Weapon Upgrade I",
"r": 1,
"c": 2,
"x": 1000,
"d": "When you craft a weapon, you can add the Brutal or Pummeling qualities to it if the weapon doesn't already have those qualities."
},
{
"n": "Weapon Upgrade II",
"r": 2,
"c": 2,
"x": 1500,
"d": "When you craft a weapon, you can add the Defensive or Dismembering qualities to it if the weapon doesn't already have those qualities. Alternatively, you add a range of ranged 5 to the weapon."
},
{
"n": "Enchant Weapons",
"r": 3,
"c": 2,
"x": 2000,
"d": "You can use your blacksmith's tools as enchanter's tools and your number of uses in the Blacksmithing expertise in place of Enchantment when crafting magic weapons."
}
],
"edges": [
[
[
0,
0
],
[
1,
0
]
],
[
[
0,
1
],
[
1,
1
]
],
[
[
0,
2
],
[
1,
2
]
],
[
[
1,
0
],
[
2,
0
]
],
[
[
1,
1
],
[
2,
1
]
],
[
[
1,
2
],
[
2,
2
]
],
[
[
2,
0
],
[
3,
0
]
],
[
[
2,
1
],
[
3,
1
]
],
[
[
2,
2
],
[
3,
2
]
]
]
},
{
"tree": "Camping",
"sub": "For getting more out of your rest",
"traits": [
{
"n": "Hearty Meals",
"r": 0,
"c": 0,
"x": 500,
"d": "As a rest activity, you can turn a normal ration into something more if you have cook's utensils. The ration becomes a hearty ration (which has an equipment card)."
},
{
"n": "Leftovers",
"r": 1,
"c": 0,
"x": 1000,
"d": "As a rest activity, you can use cook's utensils and rations to make a meal for you and each human with you. You use half as many rations as there are humans. This meal counts as rations for the rest."
},
{
"n": "Kitchen Alchemy",
"r": 2,
"c": 0,
"x": 1500,
"d": "You can use your cook's utensils instead of alchemist's tools when crafting an alchemy item."
},
{
"n": "Soothing Candies",
"r": 3,
"c": 0,
"x": 2000,
"d": "As a rest activity, you can use your cook's utensils to turn a ration into 1d10 soothing candies (which have an equipment card)."
},
{
"n": "Plotting",
"r": 0,
"c": 1,
"x": 500,
"d": "As a rest activity, choose up to three pieces of equipment you can touch. The first time you or an ally uses this equipment as part of a test before the end of your next rest, they gain a +2 bonus on the roll."
},
{
"n": "Prepare Campsite",
"r": 1,
"c": 1,
"x": 1000,
"d": "Before you rest, you can ask the Ref for the EN. If it is 5 or lower, you can use a journal, quill, and inkpot to sketch out and plan a safer campsite, increasing the EN by 1, but you can't take a rest activity."
},
{
"n": "Weakness Diagram",
"r": 2,
"c": 1,
"x": 1500,
"d": "As a rest activity, you can use a journal, quill, and inkpot to sketch a monster you have seen before. You and each ally who rests with you gains a +1 bonus to attacks against this creature until you finish another rest."
},
{
"n": "Prepare Your Gear",
"r": 3,
"c": 1,
"x": 2000,
"d": "As a rest activity, you can choose up to two pieces of gear you can touch that have UD. The number of UD these items have is increased by 1 until you finish another rest."
},
{
"n": "Song of Rest",
"r": 0,
"c": 2,
"x": 500,
"d": "As a rest activity, you can play a song on an instrument. At the end of the rest, each ally who rested with you is blessed."
},
{
"n": "Song of Travel",
"r": 1,
"c": 2,
"x": 1000,
"d": "As a rest activity, you can play a song on an instrument. At the end of the rest, each ally who rested with you gains a +2 bonus on tests related to their travel role. This bonus lasts until they finish a rest."
},
{
"n": "Delayed Inspiration",
"r": 2,
"c": 2,
"x": 1500,
"d": "When you use the Song of Rest trait, instead of your allies ending the rest blessed, they can choose to be blessed at the start of any DT before they finish their next rest. They can only make this choice once."
},
{
"n": "Bard",
"r": 3,
"c": 2,
"x": 2000,
"d": "Your Song of Rest feature allows allies to become blessed twice during the day instead of once."
}
],
"edges": [
[
[
0,
0
],
[
1,
0
]
],
[
[
0,
0
],
[
1,
1
]
],
[
[
0,
1
],
[
1,
0
]
],
[
[
0,
1
],
[
1,
1
]
],
[
[
0,
2
],
[
1,
2
]
],
[
[
1,
0
],
[
2,
0
]
],
[
[
1,
1
],
[
2,
1
]
],
[
[
1,
2
],
[
2,
2
]
],
[
[
2,
0
],
[
3,
0
]
],
[
[
2,
1
],
[
3,
1
]
],
[
[
2,
2
],
[
3,
2
]
]
]
},
{
"tree": "Chopping",
"sub": "For mastery of handaxes, axes, greataxes, and halberds",
"traits": [
{
"n": "Axe Hurler",
"r": 0,
"c": 0,
"x": 500,
"d": "While you wield a handaxe, it's non-melee range increases by 2 squares. This bonus stacks with Mighty Arm."
},
{
"n": "Mighty Arm",
"r": 1,
"c": 0,
"x": 1000,
"d": "While you wield a handaxe, it's non-melee range increases by 2 squares. This bonus stacks with Axe Hurler."
},
{
"n": "Hurl in the Dark",
"r": 2,
"c": 0,
"x": 1500,
"d": "Ranged attacks you make with handaxes don't suffer a penalty for the target being in dim light or similar concealment, and they only suffer a -2 penalty against target in darkness or similar concealment."
},
{
"n": "Double Axe",
"r": 3,
"c": 0,
"x": 2000,
"d": "When you are wielding two handaxes, you can throw both as a ranged attack, dealing double damage to the target on a hit."
},
{
"n": "Hone the Blade",
"r": 0,
"c": 1,
"x": 500,
"d": "As a rest activity, you can sharpen the blade of up to two chopping weapons. These weapons gain a +1 damage bonus that lasts until you get a tier 1 result on an attack with the weapon or you finish a rest."
},
{
"n": "Where I Want You",
"r": 1,
"c": 1,
"x": 1000,
"d": "When you get a tier 3 result on a melee chopping weapon attack against a target of your size or smaller, you can slide the target 1 square after resolving all other effects of the attack."
},
{
"n": "Stop",
"r": 2,
"c": 1,
"x": 1500,
"d": "When you hit with an opportunity attack made with a chopping weapon, the target's speed is reduced to 0 until the end of the current combat turn."
},
{
"n": "Chopping Holster",
"r": 3,
"c": 1,
"x": 2000,
"d": "You gain an additional belt slot that can only hold chopping weapons."
},
{
"n": "Chop 'Em Down",
"r": 0,
"c": 2,
"x": 500,
"d": "When you roll on the Dismember table after scoring a crit with a chopping weapon, roll twice and choose the result."
},
{
"n": "Unrelenting Death",
"r": 1,
"c": 2,
"x": 1000,
"d": "When you score a crit with a chopping weapon, any other chopping weapon attacks you make one the same turn gain a +2 bonus."
},
{
"n": "Chopping Crit",
"r": 2,
"c": 2,
"x": 1500,
"d": "You score a crit on chopping weapon attacks when the dice without modifiers equal 18, 19, or 20."
},
{
"n": "Improved Chop",
"r": 3,
"c": 2,
"x": 2000,
"d": "You score a crit on chopping weapon attacks when the dice without modifiers equal 17, 18, 19, or 20."
}
],
"edges": [
[
[
0,
0
],
[
1,
0
]
],
[
[
0,
0
],
[
1,
1
]
],
[
[
0,
0
],
[
1,
2
]
],
[
[
0,
1
],
[
1,
0
]
],
[
[
0,
1
],
[
1,
1
]
],
[
[
0,
1
],
[
1,
2
]
],
[
[
0,
2
],
[
1,
0
]
],
[
[
0,
2
],
[
1,
1
]
],
[
[
0,
2
],
[
1,
2
]
],
[
[
1,
0
],
[
2,
0
]
],
[
[
1,
1
],
[
2,
1
]
],
[
[
1,
1
],
[
2,
2
]
],
[
[
1,
2
],
[
2,
1
]
],
[
[
1,
2
],
[
2,
2
]
],
[
[
2,
0
],
[
3,
0
]
],
[
[
2,
0
],
[
3,
1
]
],
[
[
2,
1
],
[
3,
0
]
],
[
[
2,
1
],
[
3,
1
]
],
[
[
2,
2
],
[
3,
2
]
]
]
},
{
"tree": "Conjuration",
"sub": "For maximal use of conjuration spells",
"traits": [
{
"n": "Lasting Conjuration",
"r": 0,
"c": 0,
"x": 500,
"d": "When you cast a conjuration spell with a duration listed in UD, add an additional 1 UD to the duration."
},
{
"n": "Conjuration Mastery",
"r": 1,
"c": 0,
"x": 1000,
"d": "Non-doom tier 1 results of rank 0 and 1 conjuration spells you cast don't add to the chaos count. Your conjuration spells of rank 2 and higher are treated as 2 ranks lower when they trigger a backlash."
},
{
"n": "Blip",
"r": 2,
"c": 0,
"x": 1500,
"d": "When you cast a conjuration spell, you can teleport a number of squares equal to your Mind after the spell resolves."
},
{
"n": "Split Conjuration",
"r": 3,
"c": 0,
"x": 2000,
"d": "When you cast a conjuration spell that has a target of 1 creature, object, ally, enemy, or target, you can target one additional qualifying target."
},
{
"n": "Jumper",
"r": 0,
"c": 1,
"x": 500,
"d": "When you cast a conjuration spell that teleports a target, you can teleport the target an additional number of squares equal to your Mind. This trait stacks with Long Distance Jump."
},
{
"n": "Long Distance Jump",
"r": 1,
"c": 1,
"x": 1000,
"d": "When you cast a conjuration spell that teleports a target, you can teleport the target an additional number of squares equal to your Mind. This trait stacks with Jumper."
},
{
"n": "Baleful Teleport",
"r": 2,
"c": 1,
"x": 1500,
"d": "When you teleport a target with a conjuration spell, you can choose to have the target take damage equal to twice your Mind."
},
{
"n": "Portal Pocket",
"r": 3,
"c": 1,
"x": 2000,
"d": "You gain an additional belt slot that exists in an extradimensional space only you can access. If you die, any items in that slot disappear into the void."
},
{
"n": "Summoning Ward",
"r": 0,
"c": 2,
"x": 500,
"d": "Creatures you summon with conjuration spells have AD equal to their power."
},
{
"n": "Blessed Summons",
"r": 1,
"c": 2,
"x": 1000,
"d": "When you summon a creature with a conjuration spell, they are blessed."
},
{
"n": "Improved Summons",
"r": 2,
"c": 2,
"x": 1500,
"d": "When you cast a conjuration spell that allows you to summon a monster, you can summon a monster with power equal to what the spell says plus your Mind."
},
{
"n": "Telepathic Connection",
"r": 3,
"c": 2,
"x": 2000,
"d": "When you summon a creature with a conjuration spell, you can telepathically communicate with them and use their senses as your own (while still using yours) over any distance until the spell ends."
}
],
"edges": [
[
[
0,
0
],
[
1,
0
]
],
[
[
0,
0
],
[
1,
1
]
],
[
[
0,
0
],
[
1,
2
]
],
[
[
0,
1
],
[
1,
0
]
],
[
[
0,
1
],
[
1,
1
]
],
[
[
0,
1
],
[
1,
2
]
],
[
[
0,
2
],
[
1,
0
]
],
[
[
0,
2
],
[
1,
1
]
],
[
[
0,
2
],
[
1,
2
]
],
[
[
1,
0
],
[
2,
0
]
],
[
[
1,
0
],
[
2,
1
]
],
[
[
1,
1
],
[
2,
0
]
],
[
[
1,
1
],
[
2,
1
]
],
[
[
1,
2
],
[
2,
2
]
],
[
[
2,
0
],
[
3,
0
]
],
[
[
2,
0
],
[
3,
1
]
],
[
[
2,
1
],
[
3,
0
]
],
[
[
2,
1
],
[
3,
1
]
],
[
[
2,
2
],
[
3,
2
]
]
]
},
{
"tree": "Elemental",
"sub": "For maximal use of elemental spells",
"traits": [
{
"n": "Burn Baby",
"r": 0,
"c": 0,
"x": 500,
"d": "When you cast an elemental spell that deals damage to a target, the target takes additional damage equal to your Mind."
},
{
"n": "Lingering Fire",
"r": 1,
"c": 0,
"x": 1000,
"d": "At the start of your combat turn, you can choose a creature you dealt damage to with an elemental spell on your last turn (no action required). The creature takes damage equal to your Mind."
},
{
"n": "Fire Ward",
"r": 2,
"c": 0,
"x": 1500,
"d": "When you cast an elemental spell, you gain a fire ward that lasts until the start of your next combat turn. When a creature deals damage to you with a melee attack while the ward is active, they take 1d10 damage."
},
{
"n": "Burned in the Brain",
"r": 3,
"c": 0,
"x": 2000,
"d": "As a rest activity, you can absorb an elemental spellbook. The book is destroyed, and you always wield it. It occupies no slots. If you use this rest activity again, you lose previously absorbed books."
},
{
"n": "Hurl the Storm",
"r": 0,
"c": 1,
"x": 500,
"d": "When you cast a ranged elemental spell, the spell's range increases a number of squares equal to your Mind."
},
{
"n": "Elemental Mastery",
"r": 1,
"c": 1,
"x": 1000,
"d": "Non-doom tier 1 results of rank 0 and 1 conjuration spells you cast don't add to the chaos count. Your conjuration spells of rank 2 and higher are treated as 2 ranks lower when they trigger a backlash."
},
{
"n": "Selective Storm",
"r": 2,
"c": 1,
"x": 1500,
"d": "When you cast an elemental spell that affects all creatures in an area of effect, you can choose a number of creatures equal to your Mind. Those creatures aren't targeted by the spell."
},
{
"n": "Spreading Storm",
"r": 3,
"c": 1,
"x": 2000,
"d": "When you cast an elemental spell that creates an area of effect, you can increase all dimensions of the area of effect by 1."
},
{
"n": "Water Shield",
"r": 0,
"c": 2,
"x": 500,
"d": "When you cast an elemental spell, you can harness the magic to surround your body in a water ward and gain AD equal to your Mind. The AD granted by this trait disappears at the end of a rest."
},
{
"n": "Water Cannon",
"r": 1,
"c": 2,
"x": 1000,
"d": "When a Huge or smaller creature takes damage from an elemental spell you cast, you can slide the creature a number of squares equal to your Mind after the spell resolves."
},
{
"n": "Might of Waves",
"r": 2,
"c": 2,
"x": 1500,
"d": "When you force move a creature into an object with an elemental spell or the Water Cannon trait, the creature takes additional damage equal to the forced movement remaining when they collide."
},
{
"n": "Split the Sea",
"r": 3,
"c": 2,
"x": 2000,
"d": "When you cast an elemental spell that has a target of 1 creature, object, ally, enemy, or target, you can target one additional qualifying target."
}
],
"edges": [
[
[
0,
0
],
[
1,
0
]
],
[
[
0,
1
],
[
1,
1
]
],
[
[
0,
2
],
[
1,
2
]
],
[
[
1,
0
],
[
2,
0
]
],
[
[
1,
1
],
[
2,
1
]
],
[
[
1,
2
],
[
2,
2
]
],
[
[
2,
0
],
[
3,
0
]
],
[
[
2,
0
],
[
3,
1
]
],
[
[
2,
0
],
[
3,
2
]
],
[
[
2,
1
],
[
3,
0
]
],
[
[
2,
1
],
[
3,
1
]
],
[
[
2,
1
],
[
3,
2
]
],
[
[
2,
2
],
[
3,
0
]
],
[
[
2,
2
],
[
3,
1
]
],
[
[
2,
2
],
[
3,
2
]
]
]
},
{
"tree": "Enchantment",
"sub": "For creating and using magic items",
"traits": [
{
"n": "Material Transfer",
"r": 0,
"c": 0,
"x": 500,
"d": "As a rest activity, touch two armors or weapons that can be crafted from the same material but are not, such as iron heavy armor and a steel sword. The materials used in each item are magically swapped."
},
{
"n": "Enchantransfer",
"r": 1,
"c": 0,
"x": 1000,
"d": "As a rest activity, choose two weapons or two suits of armor or two shields you can touch. At least one item must be magic. The magic properties of each item are swapped with the other."
},
{
"n": "Most of Magic",
"r": 2,
"c": 0,
"x": 1500,
"d": "When you finish a rest, you gain a magic charge for each magic item worn in a slot. You can spend a charge after you make a test to give it a +1 bonus. Old charges disappear when you gain new ones."
},
{
"n": "Energy Transfer",
"r": 3,
"c": 0,
"x": 2000,
"d": "As a rest activity, choose a magic item you can touch and an item you're crafting. You destroy the magic item, and the other item gains a number of crafting points equal to the destroyed item's crafting goal."
},
{
"n": "Twice Enchanted",
"r": 0,
"c": 1,
"x": 500,
"d": "When you work on crafting an enchanting item as part of the Craft Equipment rest activity, you can make two crafting rolls for the item or make a second crafting roll for a different enchanting item."
},
{
"n": "Enchanting Epiphany",
"r": 1,
"c": 1,
"x": 1000,
"d": "When you make a crafting roll for an enchanting item, you get a crit when the dice without modifiers equal 18, 19, or 20."
},
{
"n": "Lasting Items",
"r": 2,
"c": 1,
"x": 1500,
"d": "Enchanting items you create that become useless when they have no UD gain an additional 1 UD."
},
{
"n": "Five Steps Ahead",
"r": 3,
"c": 1,
"x": 2000,
"d": "When you start crafting a new enchanting item, the item automatically gains crafting points equal to 5d10 multiplied by your Mind."
},
{
"n": "Hands for Tools",
"r": 0,
"c": 2,
"x": 500,
"d": "You don't need tools to make crafting rolls for alchemy, blacksmithing, or enchanting items."
},
{
"n": "Mind Protection",
"r": 1,
"c": 2,
"x": 1000,
"d": "When you wear a magic item in your head slot, you gain a +1 bonus to Mind RRs."
},
{
"n": "Strong Back",
"r": 2,
"c": 2,
"x": 1500,
"d": "When you wear a magic item in your waist slot, you gain a +1 bonus to Strength RRs."
},
{
"n": "Fast Feet",
"r": 3,
"c": 2,
"x": 2000,
"d": "When you wear a magic item in your feet slot, you gain a +1 bonus to Agility RRs."
}
],
"edges": [
[
[
0,
0
],
[
1,
0
]
],
[
[
0,
0
],
[
1,
1
]
],
[
[
0,
0
],
[
1,
2
]
],
[
[
0,
1
],
[
1,
0
]
],
[
[
0,
1
],
[
1,
1
]
],
[
[
0,
1
],
[
1,
2
]
],
[
[
0,
2
],
[
1,
0
]
],
[
[
0,
2
],
[
1,
1
]
],
[
[
0,
2
],
[
1,
2
]
],
[
[
1,
0
],
[
2,
0
]
],
[
[
1,
1
],
[
2,
1
]
],
[
[
1,
1
],
[
2,
2
]
],
[
[
1,
2
],
[
2,
1
]
],
[
[
1,
2
],
[
2,
2
]
],
[
[
2,
0
],
[
3,
0
]
],
[
[
2,
1
],
[
3,
1
]
],
[
[
2,
2
],
[
3,
2
]
]
]
},
{
"tree": "Illusion",
"sub": "For maximal use of illusion spells",
"traits": [
{
"n": "Lasting Illusion",
"r": 0,
"c": 0,
"x": 500,
"d": "When you cast an illusion spell with a duration listed in UD, add an additional 1 UD to the duration."
},
{
"n": "Illusion Mastery",
"r": 1,
"c": 0,
"x": 1000,
"d": "Non-doom tier 1 results of rank 0 and 1 illusion spells you cast don't add to the chaos count. Your illusion spells of rank 2 and higher are treated as 2 ranks lower when they trigger a backlash."
},
{
"n": "Big Dreams",
"r": 2,
"c": 0,
"x": 1500,
"d": "When you cast an illusion with a size (such as Small or Medium) the illusion's size increases by 1."
},
{
"n": "Split Illusion",
"r": 3,
"c": 0,
"x": 2000,
"d": "When you cast an illusion spell that has a target of 1 creature, object, ally, enemy, or target, you can target one additional qualifying target."
},
{
"n": "Long-Distance Illusion",
"r": 0,
"c": 1,
"x": 500,
"d": "When you cast a ranged illusion spell, the spell's range increases a number of squares equal to your Mind."
},
{
"n": "Mind Shatter",
"r": 1,
"c": 1,
"x": 1000,
"d": "When a creature makes one of your illusions created by an illusion spell you cast disappear by interacting with it, they take 1d6 damage."
},
{
"n": "You're a Believer",
"r": 2,
"c": 1,
"x": 1500,
"d": "When you cast an illusion spell that targets a creature, you can choose to take 1d6 P damage before you roll to gain a +1 bonus on the casting against that creature."
},
{
"n": "It's Real",
"r": 3,
"c": 1,
"x": 2000,
"d": "When you cast an illusion spell, you can choose one mundane object that is part of the illusion that becomes real until the end of the DT."
},
{
"n": "Free Light",
"r": 0,
"c": 2,
"x": 500,
"d": "When you cast an illusion spell, you can choose to have an object held or carried by your or a willing ally glow with 0/5 light until the end of the DT."
},
{
"n": "Strong Glow",
"r": 1,
"c": 2,
"x": 1000,
"d": "The light granted by your Free Light trait becomes 5/5."
},
{
"n": "Goodbye",
"r": 2,
"c": 2,
"x": 1500,
"d": "When you activate your Free Light trait, you can choose to become invisible until the end of your next combat turn instead of creating light. This invisibility ends if you attack or cast a spell."
},
{
"n": "Telepathic Connection",
"r": 3,
"c": 2,
"x": 2000,
"d": "When you use your Goodbye trait, you can choose another creature within 5 squares of your to become invisible instead of you."
}
],
"edges": [
[
[
0,
0
],
[
1,
0
]
],
[
[
0,
0
],
[
1,
1
]
],
[
[
0,
1
],
[
1,
0
]
],
[
[
0,
1
],
[
1,
1
]
],
[
[
0,
2
],
[
1,
2
]
],
[
[
1,
0
],
[
2,
0
]
],
[
[
1,
0
],
[
2,
1
]
],
[
[
1,
1
],
[
2,
0
]
],
[
[
1,
1
],
[
2,
1
]
],
[
[
1,
2
],
[
2,
2
]
],
[
[
2,
0
],
[
3,
0
]
],
[
[
2,
1
],
[
3,
1
]
],
[
[
2,
2
],
[
3,
2
]
]
]
},
{
"tree": "Knowledge",
"sub": "For recalling lore and clever improvisation",
"traits": [
{
"n": "Cram",
"r": 0,
"c": 0,
"x": 500,
"d": "When you read a lore book as a rest activity, you can read a second lore book as part of the same activity."
},
{
"n": "Specific Research",
"r": 1,
"c": 0,
"x": 1000,
"d": "As a rest activity, you can read a lore book. Instead of gaining its normal benefits, you can ask the Ref up to three questions about the book's subject, which the Ref answers honestly if the answer isn't secret."
},
{
"n": "Shared Knowledge",
"r": 2,
"c": 0,
"x": 1500,
"d": "When you read a lore book as a rest activity to gain an expertise, you can read the book aloud. If you do, choose one human who rests with you. They gain the benefit too."
},
{
"n": "Memorization",
"r": 3,
"c": 0,
"x": 2000,
"d": "As a rest activity, choose a lore book you have to study. You gain its expertise and are always wielding it even when you don't have it until you use this rest activity again."
},
{
"n": "Schematics",
"r": 0,
"c": 1,
"x": 500,
"d": "You can sketch a room with a journal, quill, and inkpot. As a rest activity, you can study the sketch. You gain a +2 bonus on tests made to interact with the room. It lasts until you finish a rest."
},
{
"n": "Quick Reference",
"r": 1,
"c": 1,
"x": 1000,
"d": "When you fail a Mind test to recall lore and have a lore book that relates to the lore, you can attempt the test again. You can use this trait a number of times equal to your Mind, regaining all uses when you finish a rest."
},
{
"n": "Expert Plan",
"r": 2,
"c": 1,
"x": 1500,
"d": "When you take the Prepare for Task rest activity and have a journal, quill, and inkpot, you can diagram your preparations to share with your allies. Each human who rests with you gains the activity's benefit."
},
{
"n": "Monster Expert",
"r": 3,
"c": 1,
"x": 2000,
"d": "When you are wielding a monster lore book and a monster is in your line of effect, you know the monster's Stamina, power, and the names of their attacks and traits."
},
{
"n": "Improvised Equipment",
"r": 0,
"c": 2,
"x": 500,
"d": "As a rest activity, you create an object that can be used as any mundane item. After using the object once to complete a task (per the Ref), it is destroyed. If the item has a duration, it's duration becomes 1 DT."
},
{
"n": "Labeled Inventory",
"r": 1,
"c": 2,
"x": 1000,
"d": "Each of your backpack slot's number is reduced by 1 (minimum 1), making it easier to pull equipment from your backpack."
},
{
"n": "Improvised Bomb",
"r": 2,
"c": 2,
"x": 1500,
"d": "As a rest activity, you can make 1 fire bomb without any materials or crafting rolls. The bomb becomes useless at the end of your next rest."
},
{
"n": "Special Item",
"r": 3,
"c": 2,
"x": 2000,
"d": "As a rest activity, choose a non- weapon, non-armor mundane item you have. You gain a +1 bonus on tests that reasonably incorporate the use of this item (per the Ref). The bonus lasts until you use this activity again."
}
],
"edges": [
[
[
0,
0
],
[
1,
0
]
],
[
[
0,
0
],
[
1,
1
]
],
[
[
0,
1
],
[
1,
0
]
],
[
[
0,
1
],
[
1,
1
]
],
[
[
0,
2
],
[
1,
2
]
],
[
[
1,
0
],
[
2,
0
]
],
[
[
1,
0
],
[
2,
1
]
],
[
[
1,
0
],
[
2,
2
]
],
[
[
1,
1
],
[
2,
0
]
],
[
[
1,
1
],
[
2,
1
]
],
[
[
1,
1
],
[
2,
2
]
],
[
[
1,
2
],
[
2,
0
]
],
[
[
1,
2
],
[
2,
1
]
],
[
[
1,
2
],
[
2,
2
]
],
[
[
2,
0
],
[
3,
0
]
],
[
[
2,
1
],
[
3,
1
]
],
[
[
2,
2
],
[
3,
2
]
]
]
},
{
"tree": "Leverage",
"sub": "For getting the most out of your equipment",
"traits": [
{
"n": "One More Spell",
"r": 0,
"c": 0,
"x": 500,
"d": "You can cast a spell from a spellbook that has no UD remaining. If you do, the spellbook is destroyed after casting the spell."
},
{
"n": "Recycling",
"r": 1,
"c": 0,
"x": 1000,
"d": "When a potion is consumed, you can retrieve the vial that is left behind. When you have 10 vials from the same potion, you can collect the residue into one vial to create a potion of that type as a rest activity."
},
{
"n": "Organ Harvester",
"r": 2,
"c": 0,
"x": 1500,
"d": "When you harvest crafting materials from the corpse of a creature, you gain an additional number of parts equal to your Mind."
},
{
"n": "Drink Fully",
"r": 3,
"c": 0,
"x": 2000,
"d": "You can consume a healing potion as an action instead of a maneuver. If you do, you don't roll dice to determine how much Stamina you regain. Instead, you gain the maximum amount the dice allow."
},
{
"n": "More for Less",
"r": 0,
"c": 1,
"x": 500,
"d": "When you roll a UD for a piece of mundane equipment that has only 1 die remaining at the start of rolling the item's dice, then you can only lose the UD on a result of 1."
},
{
"n": "Break It",
"r": 1,
"c": 1,
"x": 1000,
"d": "When you use a piece of mundane equipment as part of a test to overcome a goal and get a non-doom result on the test, you can destroy the equipment to improve the result of the test by 1 tier."
},
{
"n": "Half Portions",
"r": 2,
"c": 1,
"x": 1500,
"d": "You only need to eat half of a ration's worth of food during a rest to get the benefit of resting."
},
{
"n": "Stacks on Stacks",
"r": 3,
"c": 1,
"x": 2000,
"d": "When you carry an item with a stack limit greater than 1, its stack limit increases by 1."
},
{
"n": "Lasting Light",
"r": 0,
"c": 2,
"x": 500,
"d": "When you carry a mundane light source, its UD maximum increases by 1."
},
{
"n": "Torch Warrior",
"r": 1,
"c": 2,
"x": 1000,
"d": "You can wield a lit torch as a melee weapon with a range of melee 1 that deals 3 + A or S damage on a tier 2 result and 6 + A or S damage on a tier 3 result."
},
{
"n": "Lights Out",
"r": 2,
"c": 2,
"x": 1500,
"d": "If you damage another creature with a torch attack, you can choose to have the torch be extinguished and destroyed in the attack. The damage is doubled."
},
{
"n": "Fire Bomb",
"r": 3,
"c": 2,
"x": 2000,
"d": "You can use a lit lantern like a fire bomb. The lantern and its oil are destroyed after being used this way."
}
],
"edges": [
[
[
0,
0
],
[
1,
0
]
],
[
[
0,
0
],
[
1,
1
]
],
[
[
0,
0
],
[
1,
2
]
],
[
[
0,
1
],
[
1,
0
]
],
[
[
0,
1
],
[
1,
1
]
],
[
[
0,
1
],
[
1,
2
]
],
[
[
0,
2
],
[
1,
0
]
],
[
[
0,
2
],
[
1,
1
]
],
[
[
0,
2
],
[
1,
2
]
],
[
[
1,
0
],
[
2,
0
]
],
[
[
1,
0
],
[
2,
1
]
],
[
[
1,
1
],
[
2,
0
]
],
[
[
1,
1
],
[
2,
1
]
],
[
[
1,
2
],
[
2,
2
]
],
[
[
2,
0
],
[
3,
0
]
],
[
[
2,
1
],
[
3,
1
]
],
[
[
2,
2
],
[
3,
2
]
]
]
},
{
"tree": "Necromancy",
"sub": "For maximal use of necromancy spells",
"traits": [
{
"n": "Soul Absorption",
"r": 0,
"c": 0,
"x": 500,
"d": "When you cast a necromancy spell that kills a creature, you gain AD equal to your Mind. This AD disappears when you finish a rest."
},
{
"n": "Many Curses",
"r": 1,
"c": 0,
"x": 1000,
"d": "When you get a tier 3 result on a necromancy spell that targets a creature, you can make the target weakened. You can use this trait a number of times equal to your Mind, regaining all uses when you finish a rest."
},
{
"n": "You'll Suffer",
"r": 2,
"c": 0,
"x": 1500,
"d": "When you cast a necromancy spell that targets a creature, you can choose to take 1d6 P damage before you roll to gain a +1 bonus on the casting against that creature."
},
{
"n": "Sacrifice",
"r": 3,
"c": 0,
"x": 2000,
"d": "When you cast a necromancy spell that deals damage to creature, you can choose to take 1d6 P damage to deal additional damage with the spell equal to the damage you take."
},
{
"n": "Distant Necromancy",
"r": 0,
"c": 1,
"x": 500,
"d": "When you cast a ranged necromancy spell, the spell's range increases a number of squares equal to your Mind."
},
{
"n": "Necromancy Mastery",
"r": 1,
"c": 1,
"x": 1000,
"d": "Non-doom tier 1 results of rank 0 and 1 necromancy spells you cast don't add to the chaos count. Your necromancy spells of rank 2 and higher are treated as 2 ranks lower when they trigger a backlash."
},
{
"n": "Blessings for a Curse",
"r": 2,
"c": 1,
"x": 1500,
"d": "When you cast a necromancy spell that targets a creature, you can remove the blessed condition from you and any willing ally within 5 squares of you to make the target vulnerable."
},
{
"n": "Split Necromancy",
"r": 3,
"c": 1,
"x": 2000,
"d": "When you cast a necromancy spell that has a target of 1 creature, object, ally, enemy, or target, you can target one additional qualifying target."
},
{
"n": "Undead Fortitude",
"r": 0,
"c": 2,
"x": 500,
"d": "When you cast a necromancy spell, you don't need to breathe and can't suffocate until the end of the DT. If you are already under this effect, you can choose a willing ally within 5 squares of you to have it."
},
{
"n": "Flow Like Blood",
"r": 1,
"c": 2,
"x": 1000,
"d": "When you cast a necromancy spell, you have an amorphous body and gear until the end of the DT. While in this state, you can fit through openings that are at least 1 inch square."
},
{
"n": "Demon's Sight",
"r": 2,
"c": 2,
"x": 1500,
"d": "When you cast a necromancy spell, you treat dim light and darkness as if they were bright light until the end of the DT."
},
{
"n": "Angelic Presence",
"r": 3,
"c": 2,
"x": 2000,
"d": "When you cast a necromancy spell, enemies who are within 2 squares of you take a -1 penalty to their RRs until the end of the DT."
}
],
"edges": [
[
[
0,
0
],
[
1,
0
]
],
[
[
0,
1
],
[
1,
1
]
],
[
[
0,
2
],
[
1,
2
]
],
[
[
1,
0
],
[
2,
0
]
],
[
[
1,
1
],
[
2,
1
]
],
[
[
1,
2
],
[
2,
2
]
],
[
[
2,
0
],
[
3,
0
]
],
[
[
2,
1
],
[
3,
1
]
],
[
[
2,
2
],
[
3,
2
]
]
]
},
{
"tree": "Pets",
"sub": "For raising and commanding animals",
"traits": [
{
"n": "Buddy",
"r": 0,
"c": 0,
"x": 500,
"d": "As a rest activity, choose a number of pets you own equal to your Mind (minimum 1). You gain a +2 bonus on Mind tests made to interact with those pets until you use the activity again."
},
{
"n": "Pack Animals",
"r": 1,
"c": 0,
"x": 1000,
"d": "The Stamina maximum of each pet affected by your Buddy trait is raised by 4 multiplied by the number of pets affected by your Buddy trait."
},
{
"n": "Move Together",
"r": 2,
"c": 0,
"x": 1500,
"d": "When you use the Command maneuver, you can take the Move Speed maneuver as part of the same maneuver."
},
{
"n": "Beastheart",
"r": 3,
"c": 0,
"x": 2000,
"d": "When you take the Command maneuver, you can command up to two pets you own."
},
{
"n": "Tricks",
"r": 0,
"c": 1,
"x": 500,
"d": "While you own a pet, they gain a two expertises from the following list: Athletics, Endurance, Lift, Search, or Stealth. This trait stacks with Extra Tricks."
},
{
"n": "Travel Animal",
"r": 1,
"c": 1,
"x": 1000,
"d": "When you make a test related to the forager, guide, or scout travel role, you can have one pet you own help you. The test gains a +1 bonus."
},
{
"n": "Extra Tricks",
"r": 2,
"c": 1,
"x": 1500,
"d": "While you own a pet, they gain a two expertises from the following list: Athletics, Endurance, Lift, Search, or Stealth. This trait stacks with Tricks."
},
{
"n": "Share Food",
"r": 3,
"c": 1,
"x": 2000,
"d": "You can stack rations and animal feed in the same slot. You can eat animal feed and pets you car for can eat rations."
},
{
"n": "Mounted Speed",
"r": 0,
"c": 2,
"x": 500,
"d": "While you ride a pet you own, their speed is increased by 1."
},
{
"n": "Dungeon Critter",
"r": 1,
"c": 2,
"x": 1000,
"d": "Squeezing doesn't halve the speed of or grant a bonus to attack the pets you own."
},
{
"n": "Charge",
"r": 2,
"c": 2,
"x": 1500,
"d": "If you hit a target with a melee weapon attack while riding a pet you own after they move at least 2 squares on the same turn, the attack gains a +2 bonus to damage."
},
{
"n": "Beast of Burden",
"r": 3,
"c": 2,
"x": 2000,
"d": "At the end of a rest, choose one pet you own. This pet gains two additional backpack slots. The additional slots disappear at the end of your next rest."
}
],
"edges": [
[
[
0,
0
],
[
1,
0
]
],
[
[
0,
1
],
[
1,
1
]
],
[
[
0,
1
],
[
1,
2
]
],
[
[
0,
2
],
[
1,
1
]
],
[
[
0,
2
],
[
1,
2
]
],
[
[
1,
0
],
[
2,
0
]
],
[
[
1,
1
],
[
2,
1
]
],
[
[
1,
2
],
[
2,
2
]
],
[
[
2,
0
],
[
3,
0
]
],
[
[
2,
1
],
[
3,
1
]
],
[
[
2,
1
],
[
3,
2
]
],
[
[
2,
2
],
[
3,
1
]
],
[
[
2,
2
],
[
3,
2
]
]
]
},
{
"tree": "Reputation",
"sub": "For getting the most out of your village",
"traits": [
{
"n": "Call Daddy",
"r": 0,
"c": 0,
"x": 500,
"d": "Choose a merchant in your village. When you purchase goods from that merchant, treat their level as 1 higher. You can change your choice of merchant once every cycle."
},
{
"n": "Also Mommy",
"r": 1,
"c": 0,
"x": 1000,
"d": "Your Call Daddy trait can apply to two merchants of your choice. You can change one or both once every cycle."
},
{
"n": "Call Grandaddy",
"r": 2,
"c": 0,
"x": 1500,
"d": "Your Call Daddy trait increase the merchant's level by 2 instead of 1."
},
{
"n": "And Grandmommy",
"r": 3,
"c": 0,
"x": 2000,
"d": "Your Call Daddy trait applies to three merchants of your choice. You can change up to three once every cycle."
},
{
"n": "Discount",
"r": 0,
"c": 1,
"x": 500,
"d": "Choose a merchant in your village. You can purchase items in that merchant's shop for 5% cheaper. You can change your choice of merchant once every cycle."
},
{
"n": "Here's One for Free",
"r": 1,
"c": 1,
"x": 1000,
"d": "When you purchase 5 or more a single item that is destroyed or useless after being used (such as a torch, ration, or potion) from the merchant affected by your Discount trait, you get one of that item for free."
},
{
"n": "Double Discount",
"r": 2,
"c": 1,
"x": 1500,
"d": "Your Discount trait can apply to two merchants of your choice. You can change one or both once every cycle."
},
{
"n": "On Sale",
"r": 3,
"c": 1,
"x": 2000,
"d": "Items affect by your Discount trait are 10% cheaper for you instead of 5%."
},
{
"n": "Favorite Customer",
"r": 0,
"c": 2,
"x": 500,
"d": "Choose a merchant who crafts items in your village. When that merchant crafts an item for you, they make two crafting rolls a day instead of one. You can change your choice of merchant once every cycle."
},
{
"n": "VIP Treatment",
"r": 1,
"c": 2,
"x": 1000,
"d": "When a merchant affected by your Favorite Customer trait begins crafting an item for you, the item starts with 10% of its crafting points."
},
{
"n": "Have it in the Back",
"r": 2,
"c": 2,
"x": 1500,
"d": "You can ask the merchant affected by your Favorite Customer trait to start crafting an item you don't have the materials for. There's a 20% they have the materials and charge you 10% for the work."
},
{
"n": "Building Efficiency",
"r": 3,
"c": 2,
"x": 2000,
"d": "The merchant affected by your Favorite Customer trait operates as if they were 1 level higher than their actual level."
}
],
"edges": [
[
[
0,
0
],
[
1,
0
]
],
[
[
0,
1
],
[
1,
1
]
],
[
[
0,
2
],
[
1,
2
]
],
[
[
1,
0
],
[
2,
0
]
],
[
[
1,
1
],
[
2,
1
]
],
[
[
1,
2
],
[
2,
2
]
],
[
[
2,
0
],
[
3,
0
]
],
[
[
2,
1
],
[
3,
1
]
],
[
[
2,
2
],
[
3,
2
]
]
]
},
{
"tree": "Slashing",
"sub": "For mastery of knives, swords, greatswords, and glaives",
"traits": [
{
"n": "Finesse the Blade",
"r": 0,
"c": 0,
"x": 500,
"d": "You can use Agility instead of Strength when making an attack and dealing damage with a sword."
},
{
"n": "Swift Block",
"r": 1,
"c": 0,
"x": 1000,
"d": "You can add your Agility to the Parry quality of any slashing weapon you wield."
},
{
"n": "Knife Chucker",
"r": 2,
"c": 0,
"x": 1500,
"d": "When you wield a knife, it's non-melee range increases by 2 squares."
},
{
"n": "Double Knife",
"r": 3,
"c": 0,
"x": 2000,
"d": "When you are wielding two knives, you can throw both as a ranged attack, dealing double damage to the target on a hit."
},
{
"n": "Quickstep",
"r": 0,
"c": 1,
"x": 500,
"d": "When you use the Shift maneuver while wielding a slashing weapon, you can move 3 squares instead of 2."
},
{
"n": "Dance Away",
"r": 1,
"c": 1,
"x": 1000,
"d": "When you counter, you can take the Shift maneuver as part of the reaction while you are wielding a slashing weapon."
},
{
"n": "Follow Up",
"r": 2,
"c": 1,
"x": 1500,
"d": "When you push a target with the Knockback maneuver while wielding a slashing weapon, you can move into any space they vacated without provoking opportunity attacks as part of the maneuver."
},
{
"n": "On the Move",
"r": 3,
"c": 1,
"x": 2000,
"d": "When you deal damage to another creature with a melee slashing weapon attack you can move 1 square without provoking opportunity attacks."
},
{
"n": "Swordplay",
"r": 0,
"c": 2,
"x": 500,
"d": "You can add your Strength to the Parry quality of any slashing weapon you wield."
},
{
"n": "Interceding Blade",
"r": 1,
"c": 2,
"x": 1000,
"d": "When you wield a slashing weapon and a creature makes a weapon attack against a creature adjacent to you, you can use your reaction to cause the damage to apply your weapon before the target."
},
{
"n": "Break the Blade",
"r": 2,
"c": 2,
"x": 1500,
"d": "When an attack reduces a slashing weapon you wield to 0 AD and there is still damage left, you can reduce the remaining damage to 0. If you do, the weapon is destroyed."
},
{
"n": "Scabbard",
"r": 3,
"c": 2,
"x": 2000,
"d": "You gain an additional belt slot that can only hold slashing weapons."
}
],
"edges": [
[
[
0,
0
],
[
1,
0
]
],
[
[
0,
0
],
[
1,
1
]
],
[
[
0,
0
],
[
1,
2
]
],
[
[
0,
1
],
[
1,
0
]
],
[
[
0,
1
],
[
1,
1
]
],
[
[
0,
1
],
[
1,
2
]
],
[
[
0,
2
],
[
1,
0
]
],
[
[
0,
2
],
[
1,
1
]
],
[
[
0,
2
],
[
1,
2
]
],
[
[
1,
0
],
[
2,
0
]
],
[
[
1,
0
],
[
2,
1
]
],
[
[
1,
1
],
[
2,
0
]
],
[
[
1,
1
],
[
2,
1
]
],
[
[
1,
2
],
[
2,
2
]
],
[
[
2,
0
],
[
3,
0
]
],
[
[
2,
0
],
[
3,
1
]
],
[
[
2,
0
],
[
3,
2
]
],
[
[
2,
1
],
[
3,
0
]
],
[
[
2,
1
],
[
3,
1
]
],
[
[
2,
1
],
[
3,
2
]
],
[
[
2,
2
],
[
3,
0
]
],
[
[
2,
2
],
[
3,
1
]
],
[
[
2,
2
],
[
3,
2
]
]
]
},
{
"tree": "Stabbing",
"sub": "For mastery of stilettos, spears, warpicks, and pikes",
"traits": [
{
"n": "Javelin",
"r": 0,
"c": 0,
"x": 500,
"d": "You can make a ranged attack with a spear with a range of ranged 5."
},
{
"n": "Grappling Spear",
"r": 1,
"c": 0,
"x": 1000,
"d": "If you attach your spear to a rope, you can use it like a grappling hook."
},
{
"n": "Get Over Here",
"r": 2,
"c": 0,
"x": 1500,
"d": "When you hit with a ranged attack with a stabbing weapon attached to a rope and they are your size or smaller and not further from you than the rope's length, you can pull the target 1 square towards you."
},
{
"n": "Stabbing Holster",
"r": 3,
"c": 0,
"x": 2000,
"d": "You gain an additional belt slot that can only hold stabbing weapons."
},
{
"n": "Bury the Point",
"r": 0,
"c": 1,
"x": 500,
"d": "When you hit a creature with a melee stabbing weapon attack, you can deal twice as much damage as you normally would, but the weapon becomes useless until you use a rest activity to fix it."
},
{
"n": "Spinning Shaft",
"r": 1,
"c": 1,
"x": 1000,
"d": "When you get a tier 3 result on a melee stabbing weapon attack, choose another target within the weapon's distance. That target takes damage equal to your Strength."
},
{
"n": "Nope",
"r": 2,
"c": 1,
"x": 1500,
"d": "When you hit with an opportunity attack made with a stabbing weapon, the target's speed is reduced to 0 until the end of the current combat turn."
},
{
"n": "Wind Up",
"r": 3,
"c": 1,
"x": 2000,
"d": "While you are wielding a stabbing weapon, you can use a maneuver to prepare an attack. If you make a melee attack with the stabbing weapon this turn, it deals additional damage equal to your Strength."
},
{
"n": "Stabathon",
"r": 0,
"c": 2,
"x": 500,
"d": "When you score a crit with a stabbing weapon, any other attacks you make on the same turn gain a +2 bonus."
},
{
"n": "Triple Crit",
"r": 1,
"c": 2,
"x": 1000,
"d": "When you score a crit with a stabbing weapon, you deal triple the weapon's tier 3 damage instead of double."
},
{
"n": "Stabbing Crit",
"r": 2,
"c": 2,
"x": 1500,
"d": "You score a crit on stabbing weapon attacks when the dice without modifiers equal 18, 19, or 20."
},
{
"n": "Improved Stab",
"r": 3,
"c": 2,
"x": 2000,
"d": "You score a crit on stabbing weapon attacks when the dice without modifiers equal 17, 18, 19, or 20."
}
],
"edges": [
[
[
0,
0
],
[
1,
0
]
],
[
[
0,
1
],
[
1,
1
]
],
[
[
0,
1
],
[
1,
2
]
],
[
[
0,
2
],
[
1,
1
]
],
[
[
0,
2
],
[
1,
2
]
],
[
[
1,
0
],
[
2,
0
]
],
[
[
1,
1
],
[
2,
1
]
],
[
[
1,
1
],
[
2,
2
]
],
[
[
1,
2
],
[
2,
1
]
],
[
[
1,
2
],
[
2,
2
]
],
[
[
2,
0
],
[
3,
0
]
],
[
[
2,
0
],
[
3,
1
]
],
[
[
2,
0
],
[
3,
2
]
],
[
[
2,
1
],
[
3,
0
]
],
[
[
2,
1
],
[
3,
1
]
],
[
[
2,
1
],
[
3,
2
]
],
[
[
2,
2
],
[
3,
0
]
],
[
[
2,
2
],
[
3,
1
]
],
[
[
2,
2
],
[
3,
2
]
]
]
},
{
"tree": "Thievery",
"sub": "For breaking, entering, hiding, and sneaking",
"traits": [
{
"n": "Sieze the Advantage",
"r": 0,
"c": 0,
"x": 500,
"d": "When you hit with a weapon attack using Agility that has at least one edge and no banes, you deal additional damage equal to twice your Agility."
},
{
"n": "From the Shadows",
"r": 1,
"c": 0,
"x": 1000,
"d": "When you make a weapon attack against a target you are hidden from using Agility, the attack gains a +3 bonus instead the normal +2 bonus for being hidden."
},
{
"n": "Dark Senses",
"r": 2,
"c": 0,
"x": 1500,
"d": "While you are not wearing armor and not wielding a shield, you treat dim light and darkness as if they were bright light until the end of the DT."
},
{
"n": "Seeing Things",
"r": 3,
"c": 0,
"x": 2000,
"d": "When you get a tier 1 or 2 result a test made to hide from or sneak by another creature wile you are not wearing armor, you can reroll the test but must use the new result."
},
{
"n": "Safe Cracking",
"r": 0,
"c": 1,
"x": 500,
"d": "When you use lock picks on a test made to pick a lock, you can roll the test twice and choose either result."
},
{
"n": "Into the Pack",
"r": 1,
"c": 1,
"x": 1000,
"d": "When you use the Move Speed maneuver, you can use the Pick Up Item maneuver too. You don't need to have a free hand slot and can put the item in any free slot when you use the Pick Up Item maneuver."
},
{
"n": "Out of the Pack",
"r": 2,
"c": 1,
"x": 1500,
"d": "Each of your backpack slot's number is reduced by 1 (minimum 1)."
},
{
"n": "Bursting Purse",
"r": 3,
"c": 1,
"x": 2000,
"d": "You can carry an additional 500 gc in a coin purse."
},
{
"n": "Stealthy",
"r": 0,
"c": 2,
"x": 500,
"d": "When you make a test to hide or sneak while you are not wearing armor, you can roll the test twice and choose either result."
},
{
"n": "Above It All",
"r": 1,
"c": 2,
"x": 1000,
"d": "You gain a +2 bonus to tests made to climb, jump, swim, or do gymnastics while you are not wearing armor."
},
{
"n": "Dodgy",
"r": 2,
"c": 2,
"x": 1500,
"d": "You gain a +2 bonus on Agility RRs while you are not wearing armor."
},
{
"n": "Tumble",
"r": 3,
"c": 2,
"x": 2000,
"d": "When you take damage while not wearing armor, you can use your reaction to halve the damage. You can use this trait a number of times equal to your Agility and then must finish a rest before your use it again."
}
],
"edges": [
[
[
0,
0
],
[
1,
0
]
],
[
[
0,
0
],
[
1,
1
]
],
[
[
0,
0
],
[
1,
2
]
],
[
[
0,
1
],
[
1,
0
]
],
[
[
0,
1
],
[
1,
1
]
],
[
[
0,
1
],
[
1,
2
]
],
[
[
0,
2
],
[
1,
0
]
],
[
[
0,
2
],
[
1,
1
]
],
[
[
0,
2
],
[
1,
2
]
],
[
[
1,
0
],
[
2,
0
]
],
[
[
1,
1
],
[
2,
1
]
],
[
[
1,
2
],
[
2,
2
]
],
[
[
2,
0
],
[
3,
0
]
],
[
[
2,
1
],
[
3,
1
]
],
[
[
2,
2
],
[
3,
2
]
]
]
},
{
"tree": "Travel",
"sub": "For fast, safe, and profitable overland travel",
"traits": [
{
"n": "I Spy",
"r": 0,
"c": 0,
"x": 500,
"d": "When you make a test related to the scout role while carrying a spyglass, you can roll the test twice and choose either result."
},
{
"n": "Fade Away",
"r": 1,
"c": 0,
"x": 1000,
"d": "When you are in the scout role and carrying a spyglass and encounter other creatures while traveling, you can begin the encounter hidden from those creatures."
},
{
"n": "Must Go Faster",
"r": 2,
"c": 0,
"x": 1500,
"d": "When you are in the scout role and carrying a spyglass and encounter other creatures while traveling (not resting), you and each creature in your party can take 3d6 P damage to avoid the encounter before it starts."
},
{
"n": "Ambush",
"r": 3,
"c": 0,
"x": 2000,
"d": "When you get a tier 3 result on a test related to the scout travel role while carrying a spyglass, any creatures you encounter while traveling are surprised by you and your allies."
},
{
"n": "Orienteering",
"r": 0,
"c": 1,
"x": 500,
"d": "When you make a test related to the guide role while carrying a compass, you can roll the test twice and choose either result."
},
{
"n": "Troubadour",
"r": 1,
"c": 1,
"x": 1000,
"d": "When are in the support role while carrying a musical instrument, any test you make that grants a bonus to other travel roles has that bonus increased by 1."
},
{
"n": "Camp Builder",
"r": 2,
"c": 1,
"x": 1500,
"d": "When you are in the support role and get a tier 3 result on the test to make camp while carrying blacksmith's tools, you can ignore the normal benefits to create a camp that counts as resting outside of the Miasma."
},
{
"n": "This Way",
"r": 3,
"c": 1,
"x": 2000,
"d": "When you make a test related to the guide role while carrying a compass that doesn't result in the group getting or remaining lost, you can increase the group's distance traveled that day by 1 hex."
},
{
"n": "Foraging Expert",
"r": 0,
"c": 2,
"x": 500,
"d": "When you make a test related to the tracker roll and gain at least 1 ration, you gain 1 additional ration. This trait stacks with Food Finder."
},
{
"n": "Hunting Expert",
"r": 1,
"c": 2,
"x": 1000,
"d": "When you make a test in the tracker role to hunt carrying a bow weapon and ammunition for it, you can roll the test twice and choose either result."
},
{
"n": "Food Finder",
"r": 2,
"c": 2,
"x": 1500,
"d": "When you make a test related to the tracker role and gain at least 1 ration, you gain 1 additional ration. This trait stacks with Foraging Expert."
},
{
"n": "Specialized Hunter",
"r": 3,
"c": 2,
"x": 2000,
"d": "When you are in the tracker role while carrying a compass, you can choose two tasks in the role and make a test for both during a travel day."
}
],
"edges": [
[
[
0,
0
],
[
1,
0
]
],
[
[
0,
0
],
[
1,
1
]
],
[
[
0,
0
],
[
1,
2
]
],
[
[
0,
1
],
[
1,
0
]
],
[
[
0,
1
],
[
1,
1
]
],
[
[
0,
1
],
[
1,
2
]
],
[
[
0,
2
],
[
1,
0
]
],
[
[
0,
2
],
[
1,
1
]
],
[
[
0,
2
],
[
1,
2
]
],
[
[
1,
0
],
[
2,
0
]
],
[
[
1,
0
],
[
2,
1
]
],
[
[
1,
0
],
[
2,
2
]
],
[
[
1,
1
],
[
2,
0
]
],
[
[
1,
1
],
[
2,
1
]
],
[
[
1,
1
],
[
2,
2
]
],
[
[
1,
2
],
[
2,
0
]
],
[
[
1,
2
],
[
2,
1
]
],
[
[
1,
2
],
[
2,
2
]
],
[
[
2,
0
],
[
3,
0
]
],
[
[
2,
0
],
[
3,
1
]
],
[
[
2,
0
],
[
3,
2
]
],
[
[
2,
1
],
[
3,
0
]
],
[
[
2,
1
],
[
3,
1
]
],
[
[
2,
1
],
[
3,
2
]
],
[
[
2,
2
],
[
3,
0
]
],
[
[
2,
2
],
[
3,
1
]
],
[
[
2,
2
],
[
3,
2
]
]
]
},
{
"tree": "Unarmed",
"sub": "For mastery of kicks, punches, headbutts, and improvised weapons",
"traits": [
{
"n": "Throw Stuff",
"r": 0,
"c": 0,
"x": 500,
"d": "When you use an improvised weapon that occupies 1 slot, it has a range of melee 1/range 5."
},
{
"n": "Everything's a Mace",
"r": 1,
"c": 0,
"x": 1000,
"d": "When you use an improvised weapon, ask the Ref if it most resembles a hammer, mace, maul, or flail. The improvised weapon uses the same stats except that it has no weapon qualities."
},
{
"n": "Break Stuff",
"r": 2,
"c": 0,
"x": 1500,
"d": "When you hit with a melee attack with an improvised weapon, you can break the weapon and deal additional damage equal to your Agility or Strength (your choice)."
},
{
"n": "Bashing Benefits",
"r": 3,
"c": 0,
"x": 2000,
"d": "Any improvised weapon you wield counts as a bashing weapon and has the Pummeling quality."
},
{
"n": "Pack a Punch",
"r": 0,
"c": 1,
"x": 500,
"d": "For you, an empty hand slot is an unarmed strike that deals 2 + S or A dam on a tier 2 result and 4 + S or A dam on a tier 3 result. This unarmed strike has the Light weapon property."
},
{
"n": "Wrestle Big",
"r": 1,
"c": 1,
"x": 1000,
"d": "While you have at least 1 hand slot free, you can target creatures 1 size larger than you or smaller with the Grab maneuver."
},
{
"n": "Hard to Pin",
"r": 2,
"c": 1,
"x": 1500,
"d": "While you have at least 1 hand slot free and use the Escape Grab maneuver, you can roll twice and choose either result and if you get a tier 3 result, you can counter the grabber as part of your escape."
},
{
"n": "Pack a Big Punch",
"r": 3,
"c": 1,
"x": 2000,
"d": "While you have at least 1 hand slot free, your unarmed strikes deals additional damage equal to your Agility or Strength."
},
{
"n": "Extra Push",
"r": 0,
"c": 2,
"x": 500,
"d": "While you have at least 1 hand slot free and push a target with the Knockback maneuver, you can push them 1 additional square."
},
{
"n": "Big Push",
"r": 1,
"c": 2,
"x": 1000,
"d": "While you have at least 1 hand slot free, you can target creatures 1 size larger than you or smaller with the Knockback maneuver."
},
{
"n": "To the Walls",
"r": 2,
"c": 2,
"x": 1500,
"d": "When you force move a creature into an object while you have at least 1 hand slot free, the creature takes additional damage equal to the forced movement remaining when they collide."
},
{
"n": "You Are My Weapon",
"r": 3,
"c": 2,
"x": 2000,
"d": "When you force move a creature into another while you have at least 1 hand slot free, both creatures take damage equal to the forced movement remaining when they collide."
}
],
"edges": [
[
[
0,
0
],
[
1,
0
]
],
[
[
0,
1
],
[
1,
1
]
],
[
[
0,
2
],
[
1,
2
]
],
[
[
1,
0
],
[
2,
0
]
],
[
[
1,
1
],
[
2,
1
]
],
[
[
1,
2
],
[
2,
2
]
],
[
[
2,
0
],
[
3,
0
]
],
[
[
2,
1
],
[
3,
1
]
],
[
[
2,
2
],
[
3,
2
]
]
]
}
];
